#include "strings.h"

Pair strings[] =
{
    { 0, "xxxaep.o" },
    { 0, "xxxaep.S" },
    { 0, "xxxaesm.c" },
    { 0, "xxxaesm.o" },
    { 0, "xxxasmdefs.h" },
    { 0, "xxxcalls.c" },
    { 0, "xxxcalls.o" },
    { 0, "xxxcreate.c" },
    { 0, "xxxcreate.o" },
    { 0, "xxxelf.c" },
    { 0, "xxxelf.o" },
    { 0, "xxxenclave.c" },
    { 0, "xxxenclave.h" },
    { 0, "xxxenclave.o" },
    { 0, "xxxenter.o" },
    { 0, "xxxenter.S" },
    { 0, "xxxentersim.o" },
    { 0, "xxxentersim.S" },
    { 0, "xxxerror.c" },
    { 0, "xxxerror.o" },
    { 0, "xxxfiles.c" },
    { 0, "xxxfiles.o" },
    { 0, "xxxhexdump.c" },
    { 0, "xxxhexdump.o" },
    { 0, "xxxload.c" },
    { 0, "xxxload.o" },
    { 0, "xxxlog.h" },
    { 0, "xxxMakefile" },
    { 0, "xxxocalls.c" },
    { 0, "xxxocalls.h" },
    { 0, "xxxocalls.o" },
    { 0, "xxxquote.c" },
    { 0, "xxxquote.o" },
    { 0, "xxxREADME.md" },
    { 0, "xxxregisters.c" },
    { 0, "xxxregisters.o" },
    { 0, "xxxresult.c" },
    { 0, "xxxresult.o" },
    { 0, "xxxsgxdriver.c" },
    { 0, "xxxsgxdriver.o" },
    { 0, "xxxsgxmeasure.c" },
    { 0, "xxxsgxmeasure.o" },
    { 0, "xxxsgxtypes.c" },
    { 0, "xxxsgxtypes.o" },
    { 0, "xxxsha.c" },
    { 0, "xxxsha.o" },
    { 0, "xxxspinlock.c" },
    { 0, "xxxspinlock.o" },
    { 0, "xxxtests.c" },
    { 0, "xxxtests.o" },
    { 0, "xxxthread.c" },
    { 0, "xxxthread.o" },
    { 0, "xxxtypeinfo.c" },
    { 0, "xxxtypeinfo.o" },
    { 0, NULL },
};

long nstrings = sizeof(strings) / sizeof(strings[0]) - 1;
