# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
java_packages:
  - "openjdk-17-jre-headless"

apt_packages_code_coverage:
  - "lcov"

pip_packages_code_coverage:
  - "lcov-cobertura"
