# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

include ../../mak/defs.mak

TARGET = $(BINDIR)/bins

all:
	g++ -o $(TARGET) bins.cpp

clean:
	rm -rf $(TARGET)

distclean:

depend:
