// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SWITCHLESS_U_H
#define EDGER8R_SWITCHLESS_U_H

#include <openenclave/host.h>
#include "switchless_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_switchless_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const void* config,
    uint32_t config_size,
    oe_enclave_t** enclave);

#if (__SWITCHLESS__)
/* Switchless infrastructure methods */

oe_result_t switchless_enc_worker_thread(
    oe_enclave_t* enclave,
    switchless_control* psc);
#endif // __SWITCHLESS__

/* List of standard ecalls */

oe_result_t standard_enc_sum(
    oe_enclave_t* enclave,
    int* _retval,
    int arg1,
    int arg2);

/* List of synchronous switchless ecalls */

oe_result_t synchronous_switchless_enc_sum(
#if (__SWITCHLESS__)
    switchless_control* p_switchless_control,
#else  // __SWITCHLESS__
    oe_enclave_t* enclave,
#endif // __SWITCHLESS__
    int* _retval,
    int arg1,
    int arg2);

OE_EXTERNC_END

#endif // EDGER8R_SWITCHLESS_U_H
