// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#define OE_SYS_io_setup 0
#define OE_SYS_io_destroy 1
#define OE_SYS_io_submit 2
#define OE_SYS_io_cancel 3
#define OE_SYS_io_getevents 4
#define OE_SYS_setxattr 5
#define OE_SYS_lsetxattr 6
#define OE_SYS_fsetxattr 7
#define OE_SYS_getxattr 8
#define OE_SYS_lgetxattr 9
#define OE_SYS_fgetxattr 10
#define OE_SYS_listxattr 11
#define OE_SYS_llistxattr 12
#define OE_SYS_flistxattr 13
#define OE_SYS_removexattr 14
#define OE_SYS_lremovexattr 15
#define OE_SYS_fremovexattr 16
#define OE_SYS_getcwd 17
#define OE_SYS_lookup_dcookie 18
#define OE_SYS_eventfd2 19
#define OE_SYS_epoll_create1 20
#define OE_SYS_epoll_ctl 21
#define OE_SYS_epoll_pwait 22
#define OE_SYS_dup 23
#define OE_SYS_dup3 24
#define OE_SYS_fcntl 25
#define OE_SYS_inotify_init1 26
#define OE_SYS_inotify_add_watch 27
#define OE_SYS_inotify_rm_watch 28
#define OE_SYS_ioctl 29
#define OE_SYS_ioprio_set 30
#define OE_SYS_ioprio_get 31
#define OE_SYS_flock 32
#define OE_SYS_mknodat 33
#define OE_SYS_mkdirat 34
#define OE_SYS_unlinkat 35
#define OE_SYS_symlinkat 36
#define OE_SYS_linkat 37
#define OE_SYS_renameat 38
#define OE_SYS_umount2 39
#define OE_SYS_mount 40
#define OE_SYS_pivot_root 41
#define OE_SYS_nfsservctl 42
#define OE_SYS_statfs 43
#define OE_SYS_fstatfs 44
#define OE_SYS_truncate 45
#define OE_SYS_ftruncate 46
#define OE_SYS_fallocate 47
#define OE_SYS_faccessat 48
#define OE_SYS_chdir 49
#define OE_SYS_fchdir 50
#define OE_SYS_chroot 51
#define OE_SYS_fchmod 52
#define OE_SYS_fchmodat 53
#define OE_SYS_fchownat 54
#define OE_SYS_fchown 55
#define OE_SYS_openat 56
#define OE_SYS_close 57
#define OE_SYS_vhangup 58
#define OE_SYS_pipe2 59
#define OE_SYS_quotactl 60
#define OE_SYS_getdents64 61
#define OE_SYS_lseek 62
#define OE_SYS_read 63
#define OE_SYS_write 64
#define OE_SYS_readv 65
#define OE_SYS_writev 66
#define OE_SYS_pread64 67
#define OE_SYS_pwrite64 68
#define OE_SYS_preadv 69
#define OE_SYS_pwritev 70
#define OE_SYS_sendfile 71
#define OE_SYS_pselect6 72
#define OE_SYS_ppoll 73
#define OE_SYS_signalfd4 74
#define OE_SYS_vmsplice 75
#define OE_SYS_splice 76
#define OE_SYS_tee 77
#define OE_SYS_readlinkat 78
#define OE_SYS_newfstatat 79
#define OE_SYS_fstat 80
#define OE_SYS_sync 81
#define OE_SYS_fsync 82
#define OE_SYS_fdatasync 83
#define OE_SYS_sync_file_range 84
#define OE_SYS_timerfd_create 85
#define OE_SYS_timerfd_settime 86
#define OE_SYS_timerfd_gettime 87
#define OE_SYS_utimensat 88
#define OE_SYS_acct 89
#define OE_SYS_capget 90
#define OE_SYS_capset 91
#define OE_SYS_personality 92
#define OE_SYS_exit 93
#define OE_SYS_exit_group 94
#define OE_SYS_waitid 95
#define OE_SYS_set_tid_address 96
#define OE_SYS_unshare 97
#define OE_SYS_futex 98
#define OE_SYS_set_robust_list 99
#define OE_SYS_get_robust_list 100
#define OE_SYS_nanosleep 101
#define OE_SYS_getitimer 102
#define OE_SYS_setitimer 103
#define OE_SYS_kexec_load 104
#define OE_SYS_init_module 105
#define OE_SYS_delete_module 106
#define OE_SYS_timer_create 107
#define OE_SYS_timer_gettime 108
#define OE_SYS_timer_getoverrun 109
#define OE_SYS_timer_settime 110
#define OE_SYS_timer_delete 111
#define OE_SYS_clock_settime 112
#define OE_SYS_clock_gettime 113
#define OE_SYS_clock_getres 114
#define OE_SYS_clock_nanosleep 115
#define OE_SYS_syslog 116
#define OE_SYS_ptrace 117
#define OE_SYS_sched_setparam 118
#define OE_SYS_sched_setscheduler 119
#define OE_SYS_sched_getscheduler 120
#define OE_SYS_sched_getparam 121
#define OE_SYS_sched_setaffinity 122
#define OE_SYS_sched_getaffinity 123
#define OE_SYS_sched_yield 124
#define OE_SYS_sched_get_priority_max 125
#define OE_SYS_sched_get_priority_min 126
#define OE_SYS_sched_rr_get_interval 127
#define OE_SYS_restart_syscall 128
#define OE_SYS_kill 129
#define OE_SYS_tkill 130
#define OE_SYS_tgkill 131
#define OE_SYS_sigaltstack 132
#define OE_SYS_rt_sigsuspend 133
#define OE_SYS_rt_sigaction 134
#define OE_SYS_rt_sigprocmask 135
#define OE_SYS_rt_sigpending 136
#define OE_SYS_rt_sigtimedwait 137
#define OE_SYS_rt_sigqueueinfo 138
#define OE_SYS_rt_sigreturn 139
#define OE_SYS_setpriority 140
#define OE_SYS_getpriority 141
#define OE_SYS_reboot 142
#define OE_SYS_setregid 143
#define OE_SYS_setgid 144
#define OE_SYS_setreuid 145
#define OE_SYS_setuid 146
#define OE_SYS_setresuid 147
#define OE_SYS_getresuid 148
#define OE_SYS_setresgid 149
#define OE_SYS_getresgid 150
#define OE_SYS_setfsuid 151
#define OE_SYS_setfsgid 152
#define OE_SYS_times 153
#define OE_SYS_setpgid 154
#define OE_SYS_getpgid 155
#define OE_SYS_getsid 156
#define OE_SYS_setsid 157
#define OE_SYS_getgroups 158
#define OE_SYS_setgroups 159
#define OE_SYS_uname 160
#define OE_SYS_sethostname 161
#define OE_SYS_setdomainname 162
#define OE_SYS_getrlimit 163
#define OE_SYS_setrlimit 164
#define OE_SYS_getrusage 165
#define OE_SYS_umask 166
#define OE_SYS_prctl 167
#define OE_SYS_getcpu 168
#define OE_SYS_gettimeofday 169
#define OE_SYS_settimeofday 170
#define OE_SYS_adjtimex 171
#define OE_SYS_getpid 172
#define OE_SYS_getppid 173
#define OE_SYS_getuid 174
#define OE_SYS_geteuid 175
#define OE_SYS_getgid 176
#define OE_SYS_getegid 177
#define OE_SYS_gettid 178
#define OE_SYS_sysinfo 179
#define OE_SYS_mq_open 180
#define OE_SYS_mq_unlink 181
#define OE_SYS_mq_timedsend 182
#define OE_SYS_mq_timedreceive 183
#define OE_SYS_mq_notify 184
#define OE_SYS_mq_getsetattr 185
#define OE_SYS_msgget 186
#define OE_SYS_msgctl 187
#define OE_SYS_msgrcv 188
#define OE_SYS_msgsnd 189
#define OE_SYS_semget 190
#define OE_SYS_semctl 191
#define OE_SYS_semtimedop 192
#define OE_SYS_semop 193
#define OE_SYS_shmget 194
#define OE_SYS_shmctl 195
#define OE_SYS_shmat 196
#define OE_SYS_shmdt 197
#define OE_SYS_socket 198
#define OE_SYS_socketpair 199
#define OE_SYS_bind 200
#define OE_SYS_listen 201
#define OE_SYS_accept 202
#define OE_SYS_connect 203
#define OE_SYS_getsockname 204
#define OE_SYS_getpeername 205
#define OE_SYS_sendto 206
#define OE_SYS_recvfrom 207
#define OE_SYS_setsockopt 208
#define OE_SYS_getsockopt 209
#define OE_SYS_shutdown 210
#define OE_SYS_sendmsg 211
#define OE_SYS_recvmsg 212
#define OE_SYS_readahead 213
#define OE_SYS_brk 214
#define OE_SYS_munmap 215
#define OE_SYS_mremap 216
#define OE_SYS_add_key 217
#define OE_SYS_request_key 218
#define OE_SYS_keyctl 219
#define OE_SYS_clone 220
#define OE_SYS_execve 221
#define OE_SYS_mmap 222
#define OE_SYS_fadvise64 223
#define OE_SYS_swapon 224
#define OE_SYS_swapoff 225
#define OE_SYS_mprotect 226
#define OE_SYS_msync 227
#define OE_SYS_mlock 228
#define OE_SYS_munlock 229
#define OE_SYS_mlockall 230
#define OE_SYS_munlockall 231
#define OE_SYS_mincore 232
#define OE_SYS_madvise 233
#define OE_SYS_remap_file_pages 234
#define OE_SYS_mbind 235
#define OE_SYS_get_mempolicy 236
#define OE_SYS_set_mempolicy 237
#define OE_SYS_migrate_pages 238
#define OE_SYS_move_pages 239
#define OE_SYS_rt_tgsigqueueinfo 240
#define OE_SYS_perf_event_open 241
#define OE_SYS_accept4 242
#define OE_SYS_recvmmsg 243
#define OE_SYS_wait4 260
#define OE_SYS_prlimit64 261
#define OE_SYS_fanotify_init 262
#define OE_SYS_fanotify_mark 263
#define OE_SYS_name_to_handle_at 264
#define OE_SYS_open_by_handle_at 265
#define OE_SYS_clock_adjtime 266
#define OE_SYS_syncfs 267
#define OE_SYS_setns 268
#define OE_SYS_sendmmsg 269
#define OE_SYS_process_vm_readv 270
#define OE_SYS_process_vm_writev 271
#define OE_SYS_kcmp 272
#define OE_SYS_finit_module 273
#define OE_SYS_sched_setattr 274
#define OE_SYS_sched_getattr 275
#define OE_SYS_renameat2 276
#define OE_SYS_seccomp 277
#define OE_SYS_getrandom 278
#define OE_SYS_memfd_create 279
#define OE_SYS_bpf 280
#define OE_SYS_execveat 281
#define OE_SYS_userfaultfd 282
#define OE_SYS_membarrier 283
#define OE_SYS_mlock2 284
#define OE_SYS_copy_file_range 285
#define OE_SYS_preadv2 286
#define OE_SYS_pwritev2 287
#define OE_SYS_pkey_mprotect 288
#define OE_SYS_pkey_alloc 289
#define OE_SYS_pkey_free 290
#define OE_SYS_statx 291
#define OE_SYS_io_pgetevents 292
