// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted [[project-name]] header that is generated
// during the build. This file is generated by calling the
// sdk tool oe_edger8r against the [[project-name]].edl file.
#include "[[project-name]]_u.h"

// This is the function that the enclave will call back into to
// print a message.
int host_test(const char *msg)
{
    return fprintf(stdout, "Enclave called into host to print: %s\n", msg);
}

static oe_enclave_t* enclave = NULL;
oe_result_t open_enclave()
{
    oe_result_t result = OE_OK;
    uint32_t enclave_flags = 0;

    // Create the enclave
#ifdef _DEBUG
    enclave_flags |= OE_ENCLAVE_FLAG_DEBUG;
#endif
    result = oe_create_[[project-name]]_enclave(
#ifdef OE_USE_SGX
        "[[project-name]].signed.dll",
#elif OE_USE_OPTEE || OE_SIMULATE_OPTEE
        "[[generated-uuid]]",
#endif
        OE_ENCLAVE_TYPE_UNDEFINED,
        enclave_flags,
        NULL,
        0,
        &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
    }

    return result;
}

oe_result_t call_enclave()
{
    oe_result_t result = OE_OK;

    // Call into the enclave
    int hostResult;
    result = enclave_test(enclave, &hostResult);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_test failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
    }
    else if (hostResult != OE_OK)
    {
        fprintf(stderr, "OCALL failed: result=%u\n", hostResult);
        result = (oe_result_t)hostResult;
    }

    return result;
}


oe_result_t close_enclave()
{
    oe_result_t result = OE_OK;

    // Clean up the enclave if we created one
    if (enclave) {
        result = oe_terminate_enclave(enclave);
        if (result != OE_OK)
        {
            fprintf(
                stderr,
                "calling into oe_terminate_enclave failed: result=%u (%s)\n",
                result,
                oe_result_str(result));
        }
    }

    return result;
}
