// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted [[project-name]] header that is generated
// during the build. This file is generated by calling the
// sdk tool oe_edger8r against the [[project-name]].edl file.
#include "[[project-name]]_u.h"

// This is the function that the enclave will call back into to
// print a message.
int ocall_log(char *msg)
{
    if (fprintf(stdout, "Enclave called into host to print: %s\n", msg) < 0)
    {
        return 1;
    }
    return 0;
}

static oe_enclave_t* enclave = NULL;
int open_enclave(int argc, const char* argv[])
{
    oe_result_t result = OE_OK;
    uint32_t flags = 0;

    // Create the enclave
    result = oe_create_[[project-name]]_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        return 1;
    }

    return 0;
}

int call_enclave(char *input_msg, char *enclave_msg, unsigned int enclave_msg_count)
{
    oe_result_t result = OE_OK;

    // Call into the enclave
    int hostResult;
    result = ecall_handle_message(enclave, &hostResult, input_msg, enclave_msg, enclave_msg_count);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into ecall_handle_message failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        return 1;
    }
    else if (hostResult != 0)
    {
        fprintf(stderr, "ecall_handle_message failed: result=%u\n", hostResult);
        return 1;
    }

    return 0;
}


int close_enclave()
{
    // Clean up the enclave if we created one
    if (enclave) {
        oe_result_t result = oe_terminate_enclave(enclave);
        if (result != OE_OK)
        {
            fprintf(
                stderr,
                "calling into oe_terminate_enclave failed: result=%u (%s)\n",
                result,
                oe_result_str(result));
            return 1;
        }
    }

    return 0;
}
