// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/enclave.h>
#include <openenclave/bits/stdio.h>

// Include the trusted [[project-name]] header that is generated
// during the build. This file is generated by calling the
// sdk tool oe_edger8r against the [[project-name]].edl file.
#include "[[project-name]]_t.h"

// This is the function that the host calls. It wraps
// a message from the host before calling back out to
// the host to print a message from there.
int ecall_handle_message(char *input_msg, char *enclave_msg, unsigned int enclave_msg_size)
{
    if (snprintf(enclave_msg, enclave_msg_size, "{ \"enclave\": %s, \"signature\": \"<TODO>\" }", input_msg) < 0)
    {
        fprintf(stderr, "message handling failed\n");
        return 1;
    }

    // Call back into the host
    int retval = 0;
    oe_result_t result = ocall_log(&retval, enclave_msg);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "Call to ecall_handle_message failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        return 1;
    }

    return retval;
}
