// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/**
 * @mainpage Open Enclave SDK
 *
 * The Open Enclave SDK source code is available at
 * https://github.com/Microsoft/openenclave.
 * The documentation available here was generated by running Doxygen
 * on the Open Enclave source code. It provides detailed information
 * about the C++ APIs that the Open Enclave SDK provides to developers.
 * To browse source code, obtain samples and learn how to build,
 * please visit https://github.com/Microsoft/openenclave
 */
