# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include distribution vars
  include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Check for existing required files
  stat:
    path: "{{ item }}"
  with_items: "{{ validation_distribution_files }}"
  register: file
  failed_when: not file.stat.exists
