// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SWITCHLESS_T_H
#define EDGER8R_SWITCHLESS_T_H

#include <openenclave/enclave.h>
#include "switchless_args.h"

OE_EXTERNC_BEGIN

/* List of standard ecalls */

int standard_enc_sum(int arg1, int arg2);

int synchronous_switchless_enc_sum(int arg1, int arg2);

OE_EXTERNC_END

#endif // EDGER8R_SWITCHLESS_T_H
