/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SWITCHLESS_T_H
#define EDGER8R_SWITCHLESS_T_H

#include <openenclave/enclave.h>

#include "switchless_args.h"

#define _USE_SWITCHLESS 1

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
int standard_enc_sum(
    int arg1,
    int arg2);

int synchronous_switchless_enc_sum(
    int arg1,
    int arg2);

void batch_enc_sum(
    addition_args* args,
    size_t count);

int enc_test(
    oe_switchless_t* arg,
    int type,
    addition_args* args,
    size_t count);

/**** OCALL prototypes. ****/
oe_result_t standard_host_sum(
    int* _retval,
    int arg1,
    int arg2);

oe_result_t synchronous_switchless_host_sum(
#if _USE_SWITCHLESS
    oe_switchless_t* switchless,
#endif
    int* _retval,
    int arg1,
    int arg2);

oe_result_t batch_host_sum(
    addition_args* args,
    size_t count);

OE_EXTERNC_END

#endif // EDGER8R_SWITCHLESS_T_H
