// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#define OE_SYS_read 0
#define OE_SYS_write 1
#define OE_SYS_open 2
#define OE_SYS_close 3
#define OE_SYS_stat 4
#define OE_SYS_fstat 5
#define OE_SYS_lstat 6
#define OE_SYS_poll 7
#define OE_SYS_lseek 8
#define OE_SYS_mmap 9
#define OE_SYS_mprotect 10
#define OE_SYS_munmap 11
#define OE_SYS_brk 12
#define OE_SYS_rt_sigaction 13
#define OE_SYS_rt_sigprocmask 14
#define OE_SYS_rt_sigreturn 15
#define OE_SYS_ioctl 16
#define OE_SYS_pread64 17
#define OE_SYS_pwrite64 18
#define OE_SYS_readv 19
#define OE_SYS_writev 20
#define OE_SYS_access 21
#define OE_SYS_pipe 22
#define OE_SYS_select 23
#define OE_SYS_sched_yield 24
#define OE_SYS_mremap 25
#define OE_SYS_msync 26
#define OE_SYS_mincore 27
#define OE_SYS_madvise 28
#define OE_SYS_shmget 29
#define OE_SYS_shmat 30
#define OE_SYS_shmctl 31
#define OE_SYS_dup 32
#define OE_SYS_dup2 33
#define OE_SYS_pause 34
#define OE_SYS_nanosleep 35
#define OE_SYS_getitimer 36
#define OE_SYS_alarm 37
#define OE_SYS_setitimer 38
#define OE_SYS_getpid 39
#define OE_SYS_sendfile 40
#define OE_SYS_socket 41
#define OE_SYS_connect 42
#define OE_SYS_accept 43
#define OE_SYS_sendto 44
#define OE_SYS_recvfrom 45
#define OE_SYS_sendmsg 46
#define OE_SYS_recvmsg 47
#define OE_SYS_shutdown 48
#define OE_SYS_bind 49
#define OE_SYS_listen 50
#define OE_SYS_getsockname 51
#define OE_SYS_getpeername 52
#define OE_SYS_socketpair 53
#define OE_SYS_setsockopt 54
#define OE_SYS_getsockopt 55
#define OE_SYS_clone 56
#define OE_SYS_fork 57
#define OE_SYS_vfork 58
#define OE_SYS_execve 59
#define OE_SYS_exit 60
#define OE_SYS_wait4 61
#define OE_SYS_kill 62
#define OE_SYS_uname 63
#define OE_SYS_semget 64
#define OE_SYS_semop 65
#define OE_SYS_semctl 66
#define OE_SYS_shmdt 67
#define OE_SYS_msgget 68
#define OE_SYS_msgsnd 69
#define OE_SYS_msgrcv 70
#define OE_SYS_msgctl 71
#define OE_SYS_fcntl 72
#define OE_SYS_flock 73
#define OE_SYS_fsync 74
#define OE_SYS_fdatasync 75
#define OE_SYS_truncate 76
#define OE_SYS_ftruncate 77
#define OE_SYS_getdents 78
#define OE_SYS_getcwd 79
#define OE_SYS_chdir 80
#define OE_SYS_fchdir 81
#define OE_SYS_rename 82
#define OE_SYS_mkdir 83
#define OE_SYS_rmdir 84
#define OE_SYS_creat 85
#define OE_SYS_link 86
#define OE_SYS_unlink 87
#define OE_SYS_symlink 88
#define OE_SYS_readlink 89
#define OE_SYS_chmod 90
#define OE_SYS_fchmod 91
#define OE_SYS_chown 92
#define OE_SYS_fchown 93
#define OE_SYS_lchown 94
#define OE_SYS_umask 95
#define OE_SYS_gettimeofday 96
#define OE_SYS_getrlimit 97
#define OE_SYS_getrusage 98
#define OE_SYS_sysinfo 99
#define OE_SYS_times 100
#define OE_SYS_ptrace 101
#define OE_SYS_getuid 102
#define OE_SYS_syslog 103
#define OE_SYS_getgid 104
#define OE_SYS_setuid 105
#define OE_SYS_setgid 106
#define OE_SYS_geteuid 107
#define OE_SYS_getegid 108
#define OE_SYS_setpgid 109
#define OE_SYS_getppid 110
#define OE_SYS_getpgrp 111
#define OE_SYS_setsid 112
#define OE_SYS_setreuid 113
#define OE_SYS_setregid 114
#define OE_SYS_getgroups 115
#define OE_SYS_setgroups 116
#define OE_SYS_setresuid 117
#define OE_SYS_getresuid 118
#define OE_SYS_setresgid 119
#define OE_SYS_getresgid 120
#define OE_SYS_getpgid 121
#define OE_SYS_setfsuid 122
#define OE_SYS_setfsgid 123
#define OE_SYS_getsid 124
#define OE_SYS_capget 125
#define OE_SYS_capset 126
#define OE_SYS_rt_sigpending 127
#define OE_SYS_rt_sigtimedwait 128
#define OE_SYS_rt_sigqueueinfo 129
#define OE_SYS_rt_sigsuspend 130
#define OE_SYS_sigaltstack 131
#define OE_SYS_utime 132
#define OE_SYS_mknod 133
#define OE_SYS_uselib 134
#define OE_SYS_personality 135
#define OE_SYS_ustat 136
#define OE_SYS_statfs 137
#define OE_SYS_fstatfs 138
#define OE_SYS_sysfs 139
#define OE_SYS_getpriority 140
#define OE_SYS_setpriority 141
#define OE_SYS_sched_setparam 142
#define OE_SYS_sched_getparam 143
#define OE_SYS_sched_setscheduler 144
#define OE_SYS_sched_getscheduler 145
#define OE_SYS_sched_get_priority_max 146
#define OE_SYS_sched_get_priority_min 147
#define OE_SYS_sched_rr_get_interval 148
#define OE_SYS_mlock 149
#define OE_SYS_munlock 150
#define OE_SYS_mlockall 151
#define OE_SYS_munlockall 152
#define OE_SYS_vhangup 153
#define OE_SYS_modify_ldt 154
#define OE_SYS_pivot_root 155
#define OE_SYS__sysctl 156
#define OE_SYS_prctl 157
#define OE_SYS_arch_prctl 158
#define OE_SYS_adjtimex 159
#define OE_SYS_setrlimit 160
#define OE_SYS_chroot 161
#define OE_SYS_sync 162
#define OE_SYS_acct 163
#define OE_SYS_settimeofday 164
#define OE_SYS_mount 165
#define OE_SYS_umount2 166
#define OE_SYS_swapon 167
#define OE_SYS_swapoff 168
#define OE_SYS_reboot 169
#define OE_SYS_sethostname 170
#define OE_SYS_setdomainname 171
#define OE_SYS_iopl 172
#define OE_SYS_ioperm 173
#define OE_SYS_create_module 174
#define OE_SYS_init_module 175
#define OE_SYS_delete_module 176
#define OE_SYS_get_kernel_syms 177
#define OE_SYS_query_module 178
#define OE_SYS_quotactl 179
#define OE_SYS_nfsservctl 180
#define OE_SYS_getpmsg 181
#define OE_SYS_putpmsg 182
#define OE_SYS_afs_syscall 183
#define OE_SYS_tuxcall 184
#define OE_SYS_security 185
#define OE_SYS_gettid 186
#define OE_SYS_readahead 187
#define OE_SYS_setxattr 188
#define OE_SYS_lsetxattr 189
#define OE_SYS_fsetxattr 190
#define OE_SYS_getxattr 191
#define OE_SYS_lgetxattr 192
#define OE_SYS_fgetxattr 193
#define OE_SYS_listxattr 194
#define OE_SYS_llistxattr 195
#define OE_SYS_flistxattr 196
#define OE_SYS_removexattr 197
#define OE_SYS_lremovexattr 198
#define OE_SYS_fremovexattr 199
#define OE_SYS_tkill 200
#define OE_SYS_time 201
#define OE_SYS_futex 202
#define OE_SYS_sched_setaffinity 203
#define OE_SYS_sched_getaffinity 204
#define OE_SYS_set_thread_area 205
#define OE_SYS_io_setup 206
#define OE_SYS_io_destroy 207
#define OE_SYS_io_getevents 208
#define OE_SYS_io_submit 209
#define OE_SYS_io_cancel 210
#define OE_SYS_get_thread_area 211
#define OE_SYS_lookup_dcookie 212
#define OE_SYS_epoll_create 213
#define OE_SYS_epoll_ctl_old 214
#define OE_SYS_epoll_wait_old 215
#define OE_SYS_remap_file_pages 216
#define OE_SYS_getdents64 217
#define OE_SYS_set_tid_address 218
#define OE_SYS_restart_syscall 219
#define OE_SYS_semtimedop 220
#define OE_SYS_fadvise64 221
#define OE_SYS_timer_create 222
#define OE_SYS_timer_settime 223
#define OE_SYS_timer_gettime 224
#define OE_SYS_timer_getoverrun 225
#define OE_SYS_timer_delete 226
#define OE_SYS_clock_settime 227
#define OE_SYS_clock_gettime 228
#define OE_SYS_clock_getres 229
#define OE_SYS_clock_nanosleep 230
#define OE_SYS_exit_group 231
#define OE_SYS_epoll_wait 232
#define OE_SYS_epoll_ctl 233
#define OE_SYS_tgkill 234
#define OE_SYS_utimes 235
#define OE_SYS_vserver 236
#define OE_SYS_mbind 237
#define OE_SYS_set_mempolicy 238
#define OE_SYS_get_mempolicy 239
#define OE_SYS_mq_open 240
#define OE_SYS_mq_unlink 241
#define OE_SYS_mq_timedsend 242
#define OE_SYS_mq_timedreceive 243
#define OE_SYS_mq_notify 244
#define OE_SYS_mq_getsetattr 245
#define OE_SYS_kexec_load 246
#define OE_SYS_waitid 247
#define OE_SYS_add_key 248
#define OE_SYS_request_key 249
#define OE_SYS_keyctl 250
#define OE_SYS_ioprio_set 251
#define OE_SYS_ioprio_get 252
#define OE_SYS_inotify_init 253
#define OE_SYS_inotify_add_watch 254
#define OE_SYS_inotify_rm_watch 255
#define OE_SYS_migrate_pages 256
#define OE_SYS_openat 257
#define OE_SYS_mkdirat 258
#define OE_SYS_mknodat 259
#define OE_SYS_fchownat 260
#define OE_SYS_futimesat 261
#define OE_SYS_newfstatat 262
#define OE_SYS_unlinkat 263
#define OE_SYS_renameat 264
#define OE_SYS_linkat 265
#define OE_SYS_symlinkat 266
#define OE_SYS_readlinkat 267
#define OE_SYS_fchmodat 268
#define OE_SYS_faccessat 269
#define OE_SYS_pselect6 270
#define OE_SYS_ppoll 271
#define OE_SYS_unshare 272
#define OE_SYS_set_robust_list 273
#define OE_SYS_get_robust_list 274
#define OE_SYS_splice 275
#define OE_SYS_tee 276
#define OE_SYS_sync_file_range 277
#define OE_SYS_vmsplice 278
#define OE_SYS_move_pages 279
#define OE_SYS_utimensat 280
#define OE_SYS_epoll_pwait 281
#define OE_SYS_signalfd 282
#define OE_SYS_timerfd_create 283
#define OE_SYS_eventfd 284
#define OE_SYS_fallocate 285
#define OE_SYS_timerfd_settime 286
#define OE_SYS_timerfd_gettime 287
#define OE_SYS_accept4 288
#define OE_SYS_signalfd4 289
#define OE_SYS_eventfd2 290
#define OE_SYS_epoll_create1 291
#define OE_SYS_dup3 292
#define OE_SYS_pipe2 293
#define OE_SYS_inotify_init1 294
#define OE_SYS_preadv 295
#define OE_SYS_pwritev 296
#define OE_SYS_rt_tgsigqueueinfo 297
#define OE_SYS_perf_event_open 298
#define OE_SYS_recvmmsg 299
#define OE_SYS_fanotify_init 300
#define OE_SYS_fanotify_mark 301
#define OE_SYS_prlimit64 302
#define OE_SYS_name_to_handle_at 303
#define OE_SYS_open_by_handle_at 304
#define OE_SYS_clock_adjtime 305
#define OE_SYS_syncfs 306
#define OE_SYS_sendmmsg 307
#define OE_SYS_setns 308
#define OE_SYS_getcpu 309
#define OE_SYS_process_vm_readv 310
#define OE_SYS_process_vm_writev 311
#define OE_SYS_kcmp 312
#define OE_SYS_finit_module 313
#define OE_SYS_sched_setattr 314
#define OE_SYS_sched_getattr 315
#define OE_SYS_renameat2 316
#define OE_SYS_seccomp 317
#define OE_SYS_getrandom 318
#define OE_SYS_memfd_create 319
#define OE_SYS_kexec_file_load 320
#define OE_SYS_bpf 321
#define OE_SYS_execveat 322
#define OE_SYS_userfaultfd 323
#define OE_SYS_membarrier 324
#define OE_SYS_mlock2 325
#define OE_SYS_copy_file_range 326
#define OE_SYS_preadv2 327
#define OE_SYS_pwritev2 328
#define OE_SYS_pkey_mprotect 329
#define OE_SYS_pkey_alloc 330
#define OE_SYS_pkey_free 331
#define OE_SYS_statx 332
