#!/bin/bash

##==============================================================================
##
## Collect command-line arguments:
##
##==============================================================================

if [ "$#" != "2" ]; then
    echo "Usage: $0 TEMPLATE-DIRECTORY TEST-SOURCE"
    exit 1
fi

templatedir=$1
testsource=`/usr/bin/realpath $2`

##==============================================================================
##
## Verify that the template directory exists
##
##==============================================================================

if [ ! -d "${templatedir}" ]; then
    echo "$0: directory not found: ${templatedir}"
    exit 1
fi

if [ ! -f "${templatedir}/Makefile" ]; then
    echo "$0: required file not found: ${templatedir}/Makefile"
    exit 1
fi

main=`ls ${templatedir}/main.c*`

if [ ! -f "${main}" ]; then
    echo "$0: required file not found: ${main}"
    exit 1
fi

##==============================================================================
##
## Verify that the source file exists.
##
##==============================================================================

if [ ! -f "${testsource}" ]; then
    echo "$0: file not found: ${testsource}"
    exit 1
fi

##==============================================================================
##
## Generate the test directory name by taking the SHA-1 of the path and the
## contents of the source file.
##
##==============================================================================

filename=`/bin/tempfile`

echo ${testsource} > ${filename}
cat ${testsource} >> ${filename}

if [ ! -f "${filename}" ]; then
    echo "$0: failed to create temporary file: ${filename}"
    exit 1
fi

testdir=`sha1sum ${filename} | awk '{print $1".wraptest"}'`

##==============================================================================
##
## Copy the template directory to the test directory and substitute the source 
## file name into main.c*
##
##==============================================================================

if [ -d "${testdir}" ]; then
    echo "$0: directory already exists: ${testdir}"
    echo "$0: testsource=${testsource}"
    exit 1
fi

rm -rf ${testdir}

cp -r ${templatedir} ${testdir}
if [ ! -d "${testdir}" ]; then
    echo "$0: failed to create directory: ${testdir}"
    exit 1
fi

echo "Created ${testdir}"

main=`ls ${testdir}/main.c*`
if [ ! -f "${main}" ]; then
    echo "$0: required file not found: ${main}"
    exit 1
fi

cp ${main} ${main}.bak
if [ ! -f "${main}.bak" ]; then
    echo "$0: file not found: ${main}.bak"
    exit 1
fi

sed "s~__TEST__~${testsource}~g" ${main}.bak > ${main}
if [ "$?" != "0" ]; then
    echo "$0: substitution failed: ${main}"
    exit 1
fi

rm -rf ${main}.bak
