# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
tmp_dir: "C:\\Windows\\Temp"
shellcheck_dest: "C:\\Program Files\\shellcheck"
jenkins_agent_root_dir: "C:/Jenkins"
# From https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-21
jdk_url: "https://aka.ms/download-jdk/microsoft-jdk-21.0.11-windows-x64.msi"
# From https://aka.ms/download-jdk/microsoft-jdk-21.0.11-windows-x64.msi.sha256sum.txt
jdk_checksum: "3334d53bdda197c85485d345075af98f1e31b0ca210a116d058ab67019f10f0f"
jdk_path: "C:\\Program Files\\Microsoft\\jdk-21.0.11\\bin\\java.exe"
# This GUID is determined by installing jdk and then running the Powershell command:
# `Get-WmiObject Win32_Product | Format-Table IdentifyingNumber, Name`
jdk_productcode: "879C3E29-AA5D-4009-B30D-7F4C8EC13044"

validation_binaries:
  - "{{ jdk_path }}"
  - "C:\\Windows\\System32\\docker.exe"
