// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

struct Date
{
    uint32 mm;
    uint32 dd;
    uint32 yyyy;
};

struct Object
{
    size_t id;
    [string] char* name;
};

struct Node
{
    uint32 value;
    [one] struct Node* next;
};

function [ecall] void ReturnVoid();

function [ecall] uint32 ReturnUint32();

function [ecall, string] char* ReturnStr();

function [ecall] struct Date ReturnDate();

function [ecall] struct Object ReturnObject();

function [ecall, count=count] struct Object* ReturnObjects(
    [in] size_t count);

function [ecall, one] struct Node* ReturnLinkedList();

function [ecall, string] char* TestStrdup(
    [string, in] const char* s);

function [ecall] int32 CopyObject(
    [inout, one] struct Object* dest,
    [in, one] const struct Object* src);

function [ecall] int32 CopyObjects(
    [out] struct Object dest[2],
    [in] const struct Object src[2]);

function [ecall] int32 ECALL_MultipleParams(
    [in, string] const char* strIn,
    [in] uint32 numIn,
    [in, one] const struct Object* objectIn,
    [out, string, count=128] char* strOut,
    [out, one] uint32* numOut,
    [out, one] struct Object* objectOut,
    [out, one, ref] struct Object* objectRefOut);

function [ocall] int32 OCALL_MultipleParams(
    [in, string] const char* strIn,
    [in] uint32 numIn,
    [in, one] const struct Object* objectIn,
    [out, string, count=128] char* strOut,
    [out, one] uint32* numOut,
    [out, one] struct Object* objectOut,
    [out, one, ref] struct Object* objectRefOut);

function [ecall] int32 GetObjectRef(
    [out, ref, one] struct Object* object);

function [ecall] int32 ModifyObject(
    [inout, one] struct Object* object);

function [ecall] size_t TestStrlcpy(
    [out, string, count=dsize] char* dest,
    [in, string] const char* src,
    [in] size_t dsize);

function [ecall] size_t TestOptQualifier(
    [opt, out, string, count=p1size] char* p1,
    [opt, in, string] const char* p2,
    [in] size_t p1size);

function [ecall, opt, count=n] int* ReturnIntPtr(
    [inout, opt, count=n] int* p,
    [in] size_t n);

function [ecall] void TestCallback(
    [in, unchecked] void* func);

function [ecall] bool TestIntPtrRef(
    [out, ref, count=n] int* intPtrOut,
    [in] size_t n);

function [ecall] void TestBufferOverun(
    [out] char src[8]);

function [ecall, unchecked] void* ReturnEnclaveMemory();

function [ecall] void TestBufferCopy(
    [out, count=n] void* dest,
    [in, count=n] const void* src,
    [in] size_t n,
    [in] bool forceOverwrite);

