// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#ifndef _OE_SYS_SYSCALL_H
#define _OE_SYS_SYSCALL_H

#include <openenclave/bits/defs.h>
#include <openenclave/bits/types.h>

OE_EXTERNC_BEGIN

#define OE_SYS_read 0
#define OE_SYS_write 1
#define OE_SYS_open 2
#define OE_SYS_close 3
#define OE_SYS_stat 4
#define OE_SYS_fstat 5
#define OE_SYS_lstat 6
#define OE_SYS_poll 7
#define OE_SYS_lseek 8
#define OE_SYS_mmap 9
#define OE_SYS_mprotect 10
#define OE_SYS_munmap 11
#define OE_SYS_brk 12
#define OE_SYS_rt_sigaction 13
#define OE_SYS_rt_sigprocmask 14
#define OE_SYS_rt_sigreturn 15
#define OE_SYS_ioctl 16
#define OE_SYS_pread64 17
#define OE_SYS_pwrite64 18
#define OE_SYS_readv 19
#define OE_SYS_writev 20
#define OE_SYS_access 21
#define OE_SYS_pipe 22
#define OE_SYS_select 23
#define OE_SYS_sched_yield 24
#define OE_SYS_mremap 25
#define OE_SYS_msync 26
#define OE_SYS_mincore 27
#define OE_SYS_madvise 28
#define OE_SYS_shmget 29
#define OE_SYS_shmat 30
#define OE_SYS_shmctl 31
#define OE_SYS_dup 32
#define OE_SYS_dup2 33
#define OE_SYS_pause 34
#define OE_SYS_nanosleep 35
#define OE_SYS_getitimer 36
#define OE_SYS_alarm 37
#define OE_SYS_setitimer 38
#define OE_SYS_getpid 39
#define OE_SYS_sendfile 40
#define OE_SYS_socket 41
#define OE_SYS_connect 42
#define OE_SYS_accept 43
#define OE_SYS_sendto 44
#define OE_SYS_recvfrom 45
#define OE_SYS_sendmsg 46
#define OE_SYS_recvmsg 47
#define OE_SYS_shutdown 48
#define OE_SYS_bind 49
#define OE_SYS_listen 50
#define OE_SYS_getsockname 51
#define OE_SYS_getpeername 52
#define OE_SYS_socketpair 53
#define OE_SYS_setsockopt 54
#define OE_SYS_getsockopt 55
#define OE_SYS_clone 56
#define OE_SYS_fork 57
#define OE_SYS_vfork 58
#define OE_SYS_execve 59
#define OE_SYS_exit 60
#define OE_SYS_wait4 61
#define OE_SYS_kill 62
#define OE_SYS_uname 63
#define OE_SYS_semget 64
#define OE_SYS_semop 65
#define OE_SYS_semctl 66
#define OE_SYS_shmdt 67
#define OE_SYS_msgget 68
#define OE_SYS_msgsnd 69
#define OE_SYS_msgrcv 70
#define OE_SYS_msgctl 71
#define OE_SYS_fcntl 72
#define OE_SYS_flock 73
#define OE_SYS_fsync 74
#define OE_SYS_fdatasync 75
#define OE_SYS_truncate 76
#define OE_SYS_ftruncate 77
#define OE_SYS_getdents 78
#define OE_SYS_getcwd 79
#define OE_SYS_chdir 80
#define OE_SYS_fchdir 81
#define OE_SYS_rename 82
#define OE_SYS_mkdir 83
#define OE_SYS_rmdir 84
#define OE_SYS_creat 85
#define OE_SYS_link 86
#define OE_SYS_unlink 87
#define OE_SYS_symlink 88
#define OE_SYS_readlink 89
#define OE_SYS_chmod 90
#define OE_SYS_fchmod 91
#define OE_SYS_chown 92
#define OE_SYS_fchown 93
#define OE_SYS_lchown 94
#define OE_SYS_umask 95
#define OE_SYS_gettimeofday 96
#define OE_SYS_getrlimit 97
#define OE_SYS_getrusage 98
#define OE_SYS_sysinfo 99
#define OE_SYS_times 100
#define OE_SYS_ptrace 101
#define OE_SYS_getuid 102
#define OE_SYS_syslog 103
#define OE_SYS_getgid 104
#define OE_SYS_setuid 105
#define OE_SYS_setgid 106
#define OE_SYS_geteuid 107
#define OE_SYS_getegid 108
#define OE_SYS_setpgid 109
#define OE_SYS_getppid 110
#define OE_SYS_getpgrp 111
#define OE_SYS_setsid 112
#define OE_SYS_setreuid 113
#define OE_SYS_setregid 114
#define OE_SYS_getgroups 115
#define OE_SYS_setgroups 116
#define OE_SYS_setresuid 117
#define OE_SYS_getresuid 118
#define OE_SYS_setresgid 119
#define OE_SYS_getresgid 120
#define OE_SYS_getpgid 121
#define OE_SYS_setfsuid 122
#define OE_SYS_setfsgid 123
#define OE_SYS_getsid 124
#define OE_SYS_capget 125
#define OE_SYS_capset 126
#define OE_SYS_rt_sigpending 127
#define OE_SYS_rt_sigtimedwait 128
#define OE_SYS_rt_sigqueueinfo 129
#define OE_SYS_rt_sigsuspend 130
#define OE_SYS_sigaltstack 131
#define OE_SYS_utime 132
#define OE_SYS_mknod 133
#define OE_SYS_uselib 134
#define OE_SYS_personality 135
#define OE_SYS_ustat 136
#define OE_SYS_statfs 137
#define OE_SYS_fstatfs 138
#define OE_SYS_sysfs 139
#define OE_SYS_getpriority 140
#define OE_SYS_setpriority 141
#define OE_SYS_sched_setparam 142
#define OE_SYS_sched_getparam 143
#define OE_SYS_sched_setscheduler 144
#define OE_SYS_sched_getscheduler 145
#define OE_SYS_sched_get_priority_max 146
#define OE_SYS_sched_get_priority_min 147
#define OE_SYS_sched_rr_get_interval 148
#define OE_SYS_mlock 149
#define OE_SYS_munlock 150
#define OE_SYS_mlockall 151
#define OE_SYS_munlockall 152
#define OE_SYS_vhangup 153
#define OE_SYS_modify_ldt 154
#define OE_SYS_pivot_root 155
#define OE_SYS__sysctl 156
#define OE_SYS_prctl 157
#define OE_SYS_arch_prctl 158
#define OE_SYS_adjtimex 159
#define OE_SYS_setrlimit 160
#define OE_SYS_chroot 161
#define OE_SYS_sync 162
#define OE_SYS_acct 163
#define OE_SYS_settimeofday 164
#define OE_SYS_mount 165
#define OE_SYS_umount2 166
#define OE_SYS_swapon 167
#define OE_SYS_swapoff 168
#define OE_SYS_reboot 169
#define OE_SYS_sethostname 170
#define OE_SYS_setdomainname 171
#define OE_SYS_iopl 172
#define OE_SYS_ioperm 173
#define OE_SYS_create_module 174
#define OE_SYS_init_module 175
#define OE_SYS_delete_module 176
#define OE_SYS_get_kernel_syms 177
#define OE_SYS_query_module 178
#define OE_SYS_quotactl 179
#define OE_SYS_nfsservctl 180
#define OE_SYS_getpmsg 181
#define OE_SYS_putpmsg 182
#define OE_SYS_afs_syscall 183
#define OE_SYS_tuxcall 184
#define OE_SYS_security 185
#define OE_SYS_gettid 186
#define OE_SYS_readahead 187
#define OE_SYS_setxattr 188
#define OE_SYS_lsetxattr 189
#define OE_SYS_fsetxattr 190
#define OE_SYS_getxattr 191
#define OE_SYS_lgetxattr 192
#define OE_SYS_fgetxattr 193
#define OE_SYS_listxattr 194
#define OE_SYS_llistxattr 195
#define OE_SYS_flistxattr 196
#define OE_SYS_removexattr 197
#define OE_SYS_lremovexattr 198
#define OE_SYS_fremovexattr 199
#define OE_SYS_tkill 200
#define OE_SYS_time 201
#define OE_SYS_futex 202
#define OE_SYS_sched_setaffinity 203
#define OE_SYS_sched_getaffinity 204
#define OE_SYS_set_thread_area 205
#define OE_SYS_io_setup 206
#define OE_SYS_io_destroy 207
#define OE_SYS_io_getevents 208
#define OE_SYS_io_submit 209
#define OE_SYS_io_cancel 210
#define OE_SYS_get_thread_area 211
#define OE_SYS_lookup_dcookie 212
#define OE_SYS_epoll_create 213
#define OE_SYS_epoll_ctl_old 214
#define OE_SYS_epoll_wait_old 215
#define OE_SYS_remap_file_pages 216
#define OE_SYS_getdents64 217
#define OE_SYS_set_tid_address 218
#define OE_SYS_restart_syscall 219
#define OE_SYS_semtimedop 220
#define OE_SYS_fadvise64 221
#define OE_SYS_timer_create 222
#define OE_SYS_timer_settime 223
#define OE_SYS_timer_gettime 224
#define OE_SYS_timer_getoverrun 225
#define OE_SYS_timer_delete 226
#define OE_SYS_clock_settime 227
#define OE_SYS_clock_gettime 228
#define OE_SYS_clock_getres 229
#define OE_SYS_clock_nanosleep 230
#define OE_SYS_exit_group 231
#define OE_SYS_epoll_wait 232
#define OE_SYS_epoll_ctl 233
#define OE_SYS_tgkill 234
#define OE_SYS_utimes 235
#define OE_SYS_vserver 236
#define OE_SYS_mbind 237
#define OE_SYS_set_mempolicy 238
#define OE_SYS_get_mempolicy 239
#define OE_SYS_mq_open 240
#define OE_SYS_mq_unlink 241
#define OE_SYS_mq_timedsend 242
#define OE_SYS_mq_timedreceive 243
#define OE_SYS_mq_notify 244
#define OE_SYS_mq_getsetattr 245
#define OE_SYS_kexec_load 246
#define OE_SYS_waitid 247
#define OE_SYS_add_key 248
#define OE_SYS_request_key 249
#define OE_SYS_keyctl 250
#define OE_SYS_ioprio_set 251
#define OE_SYS_ioprio_get 252
#define OE_SYS_inotify_init 253
#define OE_SYS_inotify_add_watch 254
#define OE_SYS_inotify_rm_watch 255
#define OE_SYS_migrate_pages 256
#define OE_SYS_openat 257
#define OE_SYS_mkdirat 258
#define OE_SYS_mknodat 259
#define OE_SYS_fchownat 260
#define OE_SYS_futimesat 261
#define OE_SYS_newfstatat 262
#define OE_SYS_unlinkat 263
#define OE_SYS_renameat 264
#define OE_SYS_linkat 265
#define OE_SYS_symlinkat 266
#define OE_SYS_readlinkat 267
#define OE_SYS_fchmodat 268
#define OE_SYS_faccessat 269
#define OE_SYS_pselect6 270
#define OE_SYS_ppoll 271
#define OE_SYS_unshare 272
#define OE_SYS_set_robust_list 273
#define OE_SYS_get_robust_list 274
#define OE_SYS_splice 275
#define OE_SYS_tee 276
#define OE_SYS_sync_file_range 277
#define OE_SYS_vmsplice 278
#define OE_SYS_move_pages 279
#define OE_SYS_utimensat 280
#define OE_SYS_epoll_pwait 281
#define OE_SYS_signalfd 282
#define OE_SYS_timerfd_create 283
#define OE_SYS_eventfd 284
#define OE_SYS_fallocate 285
#define OE_SYS_timerfd_settime 286
#define OE_SYS_timerfd_gettime 287
#define OE_SYS_accept4 288
#define OE_SYS_signalfd4 289
#define OE_SYS_eventfd2 290
#define OE_SYS_epoll_create1 291
#define OE_SYS_dup3 292
#define OE_SYS_pipe2 293
#define OE_SYS_inotify_init1 294
#define OE_SYS_preadv 295
#define OE_SYS_pwritev 296
#define OE_SYS_rt_tgsigqueueinfo 297
#define OE_SYS_perf_event_open 298
#define OE_SYS_recvmmsg 299
#define OE_SYS_fanotify_init 300
#define OE_SYS_fanotify_mark 301
#define OE_SYS_prlimit64 302
#define OE_SYS_name_to_handle_at 303
#define OE_SYS_open_by_handle_at 304
#define OE_SYS_clock_adjtime 305
#define OE_SYS_syncfs 306
#define OE_SYS_sendmmsg 307
#define OE_SYS_setns 308
#define OE_SYS_getcpu 309
#define OE_SYS_process_vm_readv 310
#define OE_SYS_process_vm_writev 311
#define OE_SYS_kcmp 312
#define OE_SYS_finit_module 313
#define OE_SYS_sched_setattr 314
#define OE_SYS_sched_getattr 315
#define OE_SYS_renameat2 316
#define OE_SYS_seccomp 317
#define OE_SYS_getrandom 318
#define OE_SYS_memfd_create 319
#define OE_SYS_kexec_file_load 320
#define OE_SYS_bpf 321
#define OE_SYS_execveat 322
#define OE_SYS_userfaultfd 323
#define OE_SYS_membarrier 324
#define OE_SYS_mlock2 325
#define OE_SYS_copy_file_range 326
#define OE_SYS_preadv2 327
#define OE_SYS_pwritev2 328
#define OE_SYS_pkey_mprotect 329
#define OE_SYS_pkey_alloc 330
#define OE_SYS_pkey_free 331
#define OE_SYS_statx 332

long oe_syscall(long number, ...);

#if defined(OE_NEED_STDC_NAMES)

#define SYS_read OE_SYS_read
#define SYS_write OE_SYS_write
#define SYS_open OE_SYS_open
#define SYS_close OE_SYS_close
#define SYS_stat OE_SYS_stat
#define SYS_fstat OE_SYS_fstat
#define SYS_lstat OE_SYS_lstat
#define SYS_poll OE_SYS_poll
#define SYS_lseek OE_SYS_lseek
#define SYS_mmap OE_SYS_mmap
#define SYS_mprotect OE_SYS_mprotect
#define SYS_munmap OE_SYS_munmap
#define SYS_brk OE_SYS_brk
#define SYS_rt_sigaction OE_SYS_rt_sigaction
#define SYS_rt_sigprocmask OE_SYS_rt_sigprocmask
#define SYS_rt_sigreturn OE_SYS_rt_sigreturn
#define SYS_ioctl OE_SYS_ioctl
#define SYS_pread64 OE_SYS_pread64
#define SYS_pwrite64 OE_SYS_pwrite64
#define SYS_readv OE_SYS_readv
#define SYS_writev OE_SYS_writev
#define SYS_access OE_SYS_access
#define SYS_pipe OE_SYS_pipe
#define SYS_select OE_SYS_select
#define SYS_sched_yield OE_SYS_sched_yield
#define SYS_mremap OE_SYS_mremap
#define SYS_msync OE_SYS_msync
#define SYS_mincore OE_SYS_mincore
#define SYS_madvise OE_SYS_madvise
#define SYS_shmget OE_SYS_shmget
#define SYS_shmat OE_SYS_shmat
#define SYS_shmctl OE_SYS_shmctl
#define SYS_dup OE_SYS_dup
#define SYS_dup2 OE_SYS_dup2
#define SYS_pause OE_SYS_pause
#define SYS_nanosleep OE_SYS_nanosleep
#define SYS_getitimer OE_SYS_getitimer
#define SYS_alarm OE_SYS_alarm
#define SYS_setitimer OE_SYS_setitimer
#define SYS_getpid OE_SYS_getpid
#define SYS_sendfile OE_SYS_sendfile
#define SYS_socket OE_SYS_socket
#define SYS_connect OE_SYS_connect
#define SYS_accept OE_SYS_accept
#define SYS_sendto OE_SYS_sendto
#define SYS_recvfrom OE_SYS_recvfrom
#define SYS_sendmsg OE_SYS_sendmsg
#define SYS_recvmsg OE_SYS_recvmsg
#define SYS_shutdown OE_SYS_shutdown
#define SYS_bind OE_SYS_bind
#define SYS_listen OE_SYS_listen
#define SYS_getsockname OE_SYS_getsockname
#define SYS_getpeername OE_SYS_getpeername
#define SYS_socketpair OE_SYS_socketpair
#define SYS_setsockopt OE_SYS_setsockopt
#define SYS_getsockopt OE_SYS_getsockopt
#define SYS_clone OE_SYS_clone
#define SYS_fork OE_SYS_fork
#define SYS_vfork OE_SYS_vfork
#define SYS_execve OE_SYS_execve
#define SYS_exit OE_SYS_exit
#define SYS_wait4 OE_SYS_wait4
#define SYS_kill OE_SYS_kill
#define SYS_uname OE_SYS_uname
#define SYS_semget OE_SYS_semget
#define SYS_semop OE_SYS_semop
#define SYS_semctl OE_SYS_semctl
#define SYS_shmdt OE_SYS_shmdt
#define SYS_msgget OE_SYS_msgget
#define SYS_msgsnd OE_SYS_msgsnd
#define SYS_msgrcv OE_SYS_msgrcv
#define SYS_msgctl OE_SYS_msgctl
#define SYS_fcntl OE_SYS_fcntl
#define SYS_flock OE_SYS_flock
#define SYS_fsync OE_SYS_fsync
#define SYS_fdatasync OE_SYS_fdatasync
#define SYS_truncate OE_SYS_truncate
#define SYS_ftruncate OE_SYS_ftruncate
#define SYS_getdents OE_SYS_getdents
#define SYS_getcwd OE_SYS_getcwd
#define SYS_chdir OE_SYS_chdir
#define SYS_fchdir OE_SYS_fchdir
#define SYS_rename OE_SYS_rename
#define SYS_mkdir OE_SYS_mkdir
#define SYS_rmdir OE_SYS_rmdir
#define SYS_creat OE_SYS_creat
#define SYS_link OE_SYS_link
#define SYS_unlink OE_SYS_unlink
#define SYS_symlink OE_SYS_symlink
#define SYS_readlink OE_SYS_readlink
#define SYS_chmod OE_SYS_chmod
#define SYS_fchmod OE_SYS_fchmod
#define SYS_chown OE_SYS_chown
#define SYS_fchown OE_SYS_fchown
#define SYS_lchown OE_SYS_lchown
#define SYS_umask OE_SYS_umask
#define SYS_gettimeofday OE_SYS_gettimeofday
#define SYS_getrlimit OE_SYS_getrlimit
#define SYS_getrusage OE_SYS_getrusage
#define SYS_sysinfo OE_SYS_sysinfo
#define SYS_times OE_SYS_times
#define SYS_ptrace OE_SYS_ptrace
#define SYS_getuid OE_SYS_getuid
#define SYS_syslog OE_SYS_syslog
#define SYS_getgid OE_SYS_getgid
#define SYS_setuid OE_SYS_setuid
#define SYS_setgid OE_SYS_setgid
#define SYS_geteuid OE_SYS_geteuid
#define SYS_getegid OE_SYS_getegid
#define SYS_setpgid OE_SYS_setpgid
#define SYS_getppid OE_SYS_getppid
#define SYS_getpgrp OE_SYS_getpgrp
#define SYS_setsid OE_SYS_setsid
#define SYS_setreuid OE_SYS_setreuid
#define SYS_setregid OE_SYS_setregid
#define SYS_getgroups OE_SYS_getgroups
#define SYS_setgroups OE_SYS_setgroups
#define SYS_setresuid OE_SYS_setresuid
#define SYS_getresuid OE_SYS_getresuid
#define SYS_setresgid OE_SYS_setresgid
#define SYS_getresgid OE_SYS_getresgid
#define SYS_getpgid OE_SYS_getpgid
#define SYS_setfsuid OE_SYS_setfsuid
#define SYS_setfsgid OE_SYS_setfsgid
#define SYS_getsid OE_SYS_getsid
#define SYS_capget OE_SYS_capget
#define SYS_capset OE_SYS_capset
#define SYS_rt_sigpending OE_SYS_rt_sigpending
#define SYS_rt_sigtimedwait OE_SYS_rt_sigtimedwait
#define SYS_rt_sigqueueinfo OE_SYS_rt_sigqueueinfo
#define SYS_rt_sigsuspend OE_SYS_rt_sigsuspend
#define SYS_sigaltstack OE_SYS_sigaltstack
#define SYS_utime OE_SYS_utime
#define SYS_mknod OE_SYS_mknod
#define SYS_uselib OE_SYS_uselib
#define SYS_personality OE_SYS_personality
#define SYS_ustat OE_SYS_ustat
#define SYS_statfs OE_SYS_statfs
#define SYS_fstatfs OE_SYS_fstatfs
#define SYS_sysfs OE_SYS_sysfs
#define SYS_getpriority OE_SYS_getpriority
#define SYS_setpriority OE_SYS_setpriority
#define SYS_sched_setparam OE_SYS_sched_setparam
#define SYS_sched_getparam OE_SYS_sched_getparam
#define SYS_sched_setscheduler OE_SYS_sched_setscheduler
#define SYS_sched_getscheduler OE_SYS_sched_getscheduler
#define SYS_sched_get_priority_max OE_SYS_sched_get_priority_max
#define SYS_sched_get_priority_min OE_SYS_sched_get_priority_min
#define SYS_sched_rr_get_interval OE_SYS_sched_rr_get_interval
#define SYS_mlock OE_SYS_mlock
#define SYS_munlock OE_SYS_munlock
#define SYS_mlockall OE_SYS_mlockall
#define SYS_munlockall OE_SYS_munlockall
#define SYS_vhangup OE_SYS_vhangup
#define SYS_modify_ldt OE_SYS_modify_ldt
#define SYS_pivot_root OE_SYS_pivot_root
#define SYS__sysctl OE_SYS__sysctl
#define SYS_prctl OE_SYS_prctl
#define SYS_arch_prctl OE_SYS_arch_prctl
#define SYS_adjtimex OE_SYS_adjtimex
#define SYS_setrlimit OE_SYS_setrlimit
#define SYS_chroot OE_SYS_chroot
#define SYS_sync OE_SYS_sync
#define SYS_acct OE_SYS_acct
#define SYS_settimeofday OE_SYS_settimeofday
#define SYS_mount OE_SYS_mount
#define SYS_umount2 OE_SYS_umount2
#define SYS_swapon OE_SYS_swapon
#define SYS_swapoff OE_SYS_swapoff
#define SYS_reboot OE_SYS_reboot
#define SYS_sethostname OE_SYS_sethostname
#define SYS_setdomainname OE_SYS_setdomainname
#define SYS_iopl OE_SYS_iopl
#define SYS_ioperm OE_SYS_ioperm
#define SYS_create_module OE_SYS_create_module
#define SYS_init_module OE_SYS_init_module
#define SYS_delete_module OE_SYS_delete_module
#define SYS_get_kernel_syms OE_SYS_get_kernel_syms
#define SYS_query_module OE_SYS_query_module
#define SYS_quotactl OE_SYS_quotactl
#define SYS_nfsservctl OE_SYS_nfsservctl
#define SYS_getpmsg OE_SYS_getpmsg
#define SYS_putpmsg OE_SYS_putpmsg
#define SYS_afs_syscall OE_SYS_afs_syscall
#define SYS_tuxcall OE_SYS_tuxcall
#define SYS_security OE_SYS_security
#define SYS_gettid OE_SYS_gettid
#define SYS_readahead OE_SYS_readahead
#define SYS_setxattr OE_SYS_setxattr
#define SYS_lsetxattr OE_SYS_lsetxattr
#define SYS_fsetxattr OE_SYS_fsetxattr
#define SYS_getxattr OE_SYS_getxattr
#define SYS_lgetxattr OE_SYS_lgetxattr
#define SYS_fgetxattr OE_SYS_fgetxattr
#define SYS_listxattr OE_SYS_listxattr
#define SYS_llistxattr OE_SYS_llistxattr
#define SYS_flistxattr OE_SYS_flistxattr
#define SYS_removexattr OE_SYS_removexattr
#define SYS_lremovexattr OE_SYS_lremovexattr
#define SYS_fremovexattr OE_SYS_fremovexattr
#define SYS_tkill OE_SYS_tkill
#define SYS_time OE_SYS_time
#define SYS_futex OE_SYS_futex
#define SYS_sched_setaffinity OE_SYS_sched_setaffinity
#define SYS_sched_getaffinity OE_SYS_sched_getaffinity
#define SYS_set_thread_area OE_SYS_set_thread_area
#define SYS_io_setup OE_SYS_io_setup
#define SYS_io_destroy OE_SYS_io_destroy
#define SYS_io_getevents OE_SYS_io_getevents
#define SYS_io_submit OE_SYS_io_submit
#define SYS_io_cancel OE_SYS_io_cancel
#define SYS_get_thread_area OE_SYS_get_thread_area
#define SYS_lookup_dcookie OE_SYS_lookup_dcookie
#define SYS_epoll_create OE_SYS_epoll_create
#define SYS_epoll_ctl_old OE_SYS_epoll_ctl_old
#define SYS_epoll_wait_old OE_SYS_epoll_wait_old
#define SYS_remap_file_pages OE_SYS_remap_file_pages
#define SYS_getdents64 OE_SYS_getdents64
#define SYS_set_tid_address OE_SYS_set_tid_address
#define SYS_restart_syscall OE_SYS_restart_syscall
#define SYS_semtimedop OE_SYS_semtimedop
#define SYS_fadvise64 OE_SYS_fadvise64
#define SYS_timer_create OE_SYS_timer_create
#define SYS_timer_settime OE_SYS_timer_settime
#define SYS_timer_gettime OE_SYS_timer_gettime
#define SYS_timer_getoverrun OE_SYS_timer_getoverrun
#define SYS_timer_delete OE_SYS_timer_delete
#define SYS_clock_settime OE_SYS_clock_settime
#define SYS_clock_gettime OE_SYS_clock_gettime
#define SYS_clock_getres OE_SYS_clock_getres
#define SYS_clock_nanosleep OE_SYS_clock_nanosleep
#define SYS_exit_group OE_SYS_exit_group
#define SYS_epoll_wait OE_SYS_epoll_wait
#define SYS_epoll_ctl OE_SYS_epoll_ctl
#define SYS_tgkill OE_SYS_tgkill
#define SYS_utimes OE_SYS_utimes
#define SYS_vserver OE_SYS_vserver
#define SYS_mbind OE_SYS_mbind
#define SYS_set_mempolicy OE_SYS_set_mempolicy
#define SYS_get_mempolicy OE_SYS_get_mempolicy
#define SYS_mq_open OE_SYS_mq_open
#define SYS_mq_unlink OE_SYS_mq_unlink
#define SYS_mq_timedsend OE_SYS_mq_timedsend
#define SYS_mq_timedreceive OE_SYS_mq_timedreceive
#define SYS_mq_notify OE_SYS_mq_notify
#define SYS_mq_getsetattr OE_SYS_mq_getsetattr
#define SYS_kexec_load OE_SYS_kexec_load
#define SYS_waitid OE_SYS_waitid
#define SYS_add_key OE_SYS_add_key
#define SYS_request_key OE_SYS_request_key
#define SYS_keyctl OE_SYS_keyctl
#define SYS_ioprio_set OE_SYS_ioprio_set
#define SYS_ioprio_get OE_SYS_ioprio_get
#define SYS_inotify_init OE_SYS_inotify_init
#define SYS_inotify_add_watch OE_SYS_inotify_add_watch
#define SYS_inotify_rm_watch OE_SYS_inotify_rm_watch
#define SYS_migrate_pages OE_SYS_migrate_pages
#define SYS_openat OE_SYS_openat
#define SYS_mkdirat OE_SYS_mkdirat
#define SYS_mknodat OE_SYS_mknodat
#define SYS_fchownat OE_SYS_fchownat
#define SYS_futimesat OE_SYS_futimesat
#define SYS_newfstatat OE_SYS_newfstatat
#define SYS_unlinkat OE_SYS_unlinkat
#define SYS_renameat OE_SYS_renameat
#define SYS_linkat OE_SYS_linkat
#define SYS_symlinkat OE_SYS_symlinkat
#define SYS_readlinkat OE_SYS_readlinkat
#define SYS_fchmodat OE_SYS_fchmodat
#define SYS_faccessat OE_SYS_faccessat
#define SYS_pselect6 OE_SYS_pselect6
#define SYS_ppoll OE_SYS_ppoll
#define SYS_unshare OE_SYS_unshare
#define SYS_set_robust_list OE_SYS_set_robust_list
#define SYS_get_robust_list OE_SYS_get_robust_list
#define SYS_splice OE_SYS_splice
#define SYS_tee OE_SYS_tee
#define SYS_sync_file_range OE_SYS_sync_file_range
#define SYS_vmsplice OE_SYS_vmsplice
#define SYS_move_pages OE_SYS_move_pages
#define SYS_utimensat OE_SYS_utimensat
#define SYS_epoll_pwait OE_SYS_epoll_pwait
#define SYS_signalfd OE_SYS_signalfd
#define SYS_timerfd_create OE_SYS_timerfd_create
#define SYS_eventfd OE_SYS_eventfd
#define SYS_fallocate OE_SYS_fallocate
#define SYS_timerfd_settime OE_SYS_timerfd_settime
#define SYS_timerfd_gettime OE_SYS_timerfd_gettime
#define SYS_accept4 OE_SYS_accept4
#define SYS_signalfd4 OE_SYS_signalfd4
#define SYS_eventfd2 OE_SYS_eventfd2
#define SYS_epoll_create1 OE_SYS_epoll_create1
#define SYS_dup3 OE_SYS_dup3
#define SYS_pipe2 OE_SYS_pipe2
#define SYS_inotify_init1 OE_SYS_inotify_init1
#define SYS_preadv OE_SYS_preadv
#define SYS_pwritev OE_SYS_pwritev
#define SYS_rt_tgsigqueueinfo OE_SYS_rt_tgsigqueueinfo
#define SYS_perf_event_open OE_SYS_perf_event_open
#define SYS_recvmmsg OE_SYS_recvmmsg
#define SYS_fanotify_init OE_SYS_fanotify_init
#define SYS_fanotify_mark OE_SYS_fanotify_mark
#define SYS_prlimit64 OE_SYS_prlimit64
#define SYS_name_to_handle_at OE_SYS_name_to_handle_at
#define SYS_open_by_handle_at OE_SYS_open_by_handle_at
#define SYS_clock_adjtime OE_SYS_clock_adjtime
#define SYS_syncfs OE_SYS_syncfs
#define SYS_sendmmsg OE_SYS_sendmmsg
#define SYS_setns OE_SYS_setns
#define SYS_getcpu OE_SYS_getcpu
#define SYS_process_vm_readv OE_SYS_process_vm_readv
#define SYS_process_vm_writev OE_SYS_process_vm_writev
#define SYS_kcmp OE_SYS_kcmp
#define SYS_finit_module OE_SYS_finit_module
#define SYS_sched_setattr OE_SYS_sched_setattr
#define SYS_sched_getattr OE_SYS_sched_getattr
#define SYS_renameat2 OE_SYS_renameat2
#define SYS_seccomp OE_SYS_seccomp
#define SYS_getrandom OE_SYS_getrandom
#define SYS_memfd_create OE_SYS_memfd_create
#define SYS_kexec_file_load OE_SYS_kexec_file_load
#define SYS_bpf OE_SYS_bpf
#define SYS_execveat OE_SYS_execveat
#define SYS_userfaultfd OE_SYS_userfaultfd
#define SYS_membarrier OE_SYS_membarrier
#define SYS_mlock2 OE_SYS_mlock2
#define SYS_copy_file_range OE_SYS_copy_file_range
#define SYS_preadv2 OE_SYS_preadv2
#define SYS_pwritev2 OE_SYS_pwritev2
#define SYS_pkey_mprotect OE_SYS_pkey_mprotect
#define SYS_pkey_alloc OE_SYS_pkey_alloc
#define SYS_pkey_free OE_SYS_pkey_free
#define SYS_statx OE_SYS_statx

#endif /* defined(OE_NEED_STDC_NAMES) */

OE_EXTERNC_END

#endif /* _OE_SYS_SYSCALL_H */
