// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <stdio.h>

#include <openenclave/host.h>

// Include the untrusted [[project-name]] header that is generated
// during the build. This file is generated by calling the
// SDK's oeedger8r tool against the [[project-name]].edl file.
#include "[[project-name]]_u.h"

static oe_enclave_t* g_enclave = NULL;

bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--simulate") == 0)
        {
            fprintf(stdout, "Running in simulation mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;

            return true;
        }
    }

    return false;
}

bool check_debug_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--debug") == 0)
        {
            fprintf(stdout, "Running in debug mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;

            return true;
        }
    }

    return false;
}

// This is the function that the enclave will call back into to print a message.
int ocall_log(char* msg)
{
    if (fprintf(stdout, "Enclave called into host to print: %s\n", msg) < 0)
    {
        return 1;
    }

    return 0;
}

int create_enclave(int argc, const char* argv[])
{
    oe_result_t result = OE_OK;
    uint32_t flags = 0;

    if (check_debug_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_DEBUG;
    }

    if (check_simulate_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    // Create the enclave.
    result = oe_create_[[project-name]]_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &g_enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));

        return 1;
    }

    return 0;
}

int call_enclave(
    char* input_msg,
    char* enclave_msg,
    unsigned int enclave_msg_count)
{
    oe_result_t result = OE_OK;
    int hostResult;

    // Call into the enclave.
    result = ecall_handle_message(
        g_enclave, &hostResult, input_msg, enclave_msg, enclave_msg_count);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into ecall_handle_message failed: result=%u (%s)\n",
            result,
            oe_result_str(result));

        return 1;
    }
    else if (hostResult != 0)
    {
        fprintf(stderr, "ecall_handle_message failed: result=%u\n", hostResult);

        return 1;
    }

    return 0;
}

int terminate_enclave()
{
    oe_result_t result;

    // Clean up the enclave if we created one.
    if (g_enclave)
    {
        result = oe_terminate_enclave(g_enclave);
        if (result != OE_OK)
        {
            fprintf(
                stderr,
                "calling into oe_terminate_enclave failed: result=%u (%s)\n",
                result,
                oe_result_str(result));

            return 1;
        }
    }

    return 0;
}
