# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

FROM ubuntu:16.04

COPY scripts/ansible /ansible

RUN /ansible/install-ansible.sh && \
    ansible localhost --playbook-dir=/ansible -m import_role -a "name=linux/openenclave tasks_from=environment-setup.yml" -vvv && \
    /ansible/remove-ansible.sh && \
    rm -rf /ansible && \
    apt-get install --no-install-recommends -y lsb-release wget ca-certificates git
