pipeline {
  agent any
  stages {
    stage('Precommit-checking') {
      agent {
        docker {
          image 'oetools-azure:1.2'
        }

      }
      steps {
        sh 'bash ./scripts/check-precommit-reqs'
      }
    }
    stage('Build and Test') {
      parallel {
        stage('Simulation SGX1 Debug') {
          agent {
            docker {
              image 'oetools-azure:1.2'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -b Debug'
          }
        }
        stage('Simulation SGX1 Release') {
          agent {
            docker {
              image 'oetools-azure:1.2'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1 -b Release'
          }
        }
        stage('Simulation SGX1 RelWithDebInfo') {
          agent {
            docker {
              image 'oetools-azure:1.2'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1 -b RelWithDebInfo'
          }
        }
        stage('Simulation SGX1-FLC Debug') {
          agent {
            docker {
              image 'oetools-azure:1.2'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1FLC -b Debug'
          }
        }
        stage('Simulation SGX1-FLC Release') {
          agent {
            docker {
              image 'oetools-azure:1.2'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1FLC -b Release'
          }
        }
        stage('Simulation SGX1-FLC RelWithDebInfo') {
          agent {
            docker {
              image 'oetools-azure:1.2'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1FLC -b RelWithDebInfo'
          }
        }
        stage('Kabylake SGX1 Debug') {
          agent {
            node {
              label 'SGX'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1 -b Debug -d'
          }
        }
        stage('Kabylake SGX1 Release') {
          agent {
            node {
              label 'SGX'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1 -b Release -d'
          }
        }
        stage('Kabylake SGX1 RelWithDebInfo') {
          agent {
            node {
              label 'SGX'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1 -b RelWithDebInfo -d'
          }
        }
        stage('Coffeelake SGX1-FLC Debug') {
          agent {
            node {
              label 'hardware'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1FLC -b Debug -d'
          }
        }
        stage('Coffeelake SGX1-FLC Release') {
          agent {
            node {
              label 'hardware'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1FLC -b Release -d'
          }
        }
        stage('Coffeelake SGX1-FLC RelWithDebInfo') {
          agent {
            node {
              label 'hardware'
            }

          }
          steps {
            sh 'bash ./scripts/test-build-config -p SGX1FLC -b RelWithDebInfo -d'
          }
        }
      }
    }
  }
}
