// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <stdio.h>
#include <openenclave/bits/log-enc.h>

// Include the trusted logs header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the logs.edl file.
#include "logs_t.h"

// This is the function that the host calls. It sends
// log messages to the host to store in a log file.
void enclave_logs()
{
    //oe_log_info("sample", "entering enclave");
    oe_log(LOG_INFO, "sample", "entering enclave");
    for (int i=0; i<10; i++)
    {
        //oe_log_debug("sample", "loop %s #%d", "iteration", i+1);
        oe_log(LOG_DEBUG, "sample", "loop %s #%d", "iteration", i+1);
    }
    //oe_log_trace("sample", "end of loop");
    oe_log(LOG_TRACE, "sample", "end of loop");
}
