#!/bin/bash

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

if [ -f ../environment ]; then
  # shellcheck disable=SC1091  
  source ../environment
fi

make
make run
