/* Copyright (c) Microsoft Corporation. All rights reserved. */
/* Licensed under the MIT License. */
#include <windows.h>
#include <stdint.h>
#include <OpteeCalls.h>
#include <openenclave/host.h>
#include <assert.h>
#include "../oeshim_host.h"
#include "../optee_common.h"

#undef oe_call_enclave_function

BOOL /* Returns TRUE on success, FALSE on failure. */
_oe_OcallDemux(
    _In_                            uint32_t               rpcType,
    _In_reads_bytes_(rpcInputSize)  const void *           rpcInputBuffer,
    _In_                            uint32_t               rpcInputSize,
    _Out_writes_bytes_to_(
        rpcOutputSize,
        *rpcOutputSizeWritten)      void *                 rpcOutputBuffer,
    _In_                            uint32_t               rpcOutputSize,
    _Out_                           uint32_t *             rpcOutputSizeWritten,
    _In_                            ocall_table_v2_t*      ocall_table)
{
    size_t bytes_written;
    oe_result_t result = ocall_demux(rpcType, rpcInputBuffer, rpcInputSize,
                                     rpcOutputBuffer, rpcOutputSize,
                                     &bytes_written,
                                     ocall_table);
    if (result != OE_OK) {
        return FALSE;
    }

    *rpcOutputSizeWritten = bytes_written;
    return TRUE;
}

BOOL /* Returns TRUE on success, FALSE on failure. */
OPTEE_CALL
OpteeRpcCallback(
    _In_opt_                        void *         rpcCallbackContext,
    _In_                            uint32_t       rpcType,
    _In_reads_bytes_(rpcInputSize)  const void *   rpcInputBuffer,
    _In_                            uint32_t       rpcInputSize,
    _Out_writes_bytes_to_(
        rpcOutputSize,
        *rpcOutputSizeWritten)      void *         rpcOutputBuffer,
    _In_                            uint32_t       rpcOutputSize,
    _Out_                           uint32_t *     rpcOutputSizeWritten)
{
    OE_UNUSED(rpcCallbackContext);

    if (rpcType < V1_FUNCTION_ID_OFFSET) {
        /* Handle internal ECALL generated by oeedger8r. */
        return _oe_OcallDemux(rpcType,
            rpcInputBuffer, rpcInputSize, rpcOutputBuffer, rpcOutputSize, rpcOutputSizeWritten,
            &g_internal_ocall_table_v2);
    }

    if (rpcType < V2_FUNCTION_ID_OFFSET) {
        /* We shouldn't ever get an ECALL generated by sgx_edger8r */
        assert(FALSE);
    }

    /* Handle ECALL generated by oeedger8r. */
    return _oe_OcallDemux(rpcType - V2_FUNCTION_ID_OFFSET, rpcInputBuffer, rpcInputSize,
                          rpcOutputBuffer, rpcOutputSize, rpcOutputSizeWritten,
                          &g_ocall_table_v2);
}

BOOL
CallTrEEService(
    _In_ HANDLE ServiceHandle,
    _In_ ULONG FunctionCode,
    _In_reads_bytes_(InputBufferLength) PVOID InputBufferPtr,
    _In_ ULONG InputBufferLength,
    _Out_writes_bytes_to_(OutputBufferLength, *BytesWritten) PVOID OutputBufferPtr,
    _In_ ULONG OutputBufferLength,
    _Out_ PULONG BytesWrittenPtr)
{
    ULONG inputBufferSize = InputBufferLength;
    ULONG outputBufferSize = OutputBufferLength;
    PVOID inputBuffer = InputBufferPtr;
    PVOID outputBuffer = OutputBufferPtr;
    char dummyInputBuffer[1];
    char dummyOutputBuffer[1];

    if (inputBuffer == NULL) {
        inputBuffer = dummyInputBuffer;
        inputBufferSize = 1;
    }

    if (outputBuffer == NULL) {
        outputBuffer = dummyOutputBuffer;
        outputBufferSize = 1;
    }

    BOOL isSuccess = CallOpteeCommand(
        ServiceHandle,
        FunctionCode,
        inputBuffer, inputBufferSize,
        outputBuffer, outputBufferSize,
        BytesWrittenPtr,
        OpteeRpcCallback,
        NULL); /* Context to pass to ocall callback. */

    return isSuccess;
}

oe_result_t oe_call_internal_enclave_function(
    _In_ oe_enclave_t* enclave,
    _In_ uint32_t function_id,
    _In_reads_bytes_(input_buffer_size) void* input_buffer,
    _In_ size_t input_buffer_size,
    _Out_writes_bytes_to_(output_buffer_size, *output_bytes_written) void* output_buffer,
    _In_ size_t output_buffer_size,
    _Out_opt_ size_t* output_bytes_written)
{
    BOOL ret;
    HANDLE serviceHandle = (HANDLE)enclave;
    size_t bytes_written = 0;

    ret = CallTrEEService(serviceHandle,
        function_id,
        input_buffer,
        input_buffer_size,
        output_buffer,
        output_buffer_size,
        &bytes_written);

    if (output_bytes_written != NULL) {
        *output_bytes_written = bytes_written;
    }

    return (ret) ? OE_OK : OE_UNEXPECTED;
}

oe_result_t oe_call_enclave_function( 
    _In_ oe_enclave_t* enclave,
    _In_ uint32_t function_id,
    _In_reads_bytes_(input_buffer_size) void* input_buffer,
    _In_ size_t input_buffer_size,
    _Out_writes_bytes_to_(output_buffer_size, *output_bytes_written) void* output_buffer,
    _In_ size_t output_buffer_size,
    _Out_opt_ size_t* output_bytes_written)
{
    return oe_call_internal_enclave_function(enclave,
                                             V2_FUNCTION_ID_OFFSET + function_id,
                                             input_buffer,
                                             input_buffer_size,
                                             output_buffer,
                                             output_buffer_size,
                                             output_bytes_written);
}
