// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

library "OpenEnclaveJenkinsLibrary@${params.OECI_LIB_VERSION}"
GLOBAL_ERROR = globalvars.GLOBAL_ERROR

properties(
    [
        buildDiscarder(
            logRotator(
                artifactDaysToKeepStr: '90',
                artifactNumToKeepStr: '180',
                daysToKeepStr: '90',
                numToKeepStr: '180'
            )
        ),
        [$class: 'JobRestrictionProperty'],
        parameters(
            [
                string(name: 'REPOSITORY_NAME',             defaultValue: 'openenclave/openenclave', description: 'GitHub repository to build.'),
                string(name: 'BRANCH_NAME',                 defaultValue: 'master',                  description: 'Git branch to build.'),
                string(name: 'DOCKER_TAG',                  defaultValue: 'latest',                  description: 'Tag used to pull oetools docker image.'),
                string(name: 'OECI_LIB_VERSION',            defaultValue: 'master',                  description: 'Version of OE Libraries to use'),
                string(name: 'UBUNTU_NONSGX_CUSTOM_LABEL',  defaultValue: '',                        description: '[Optional] Jenkins agent label to use for Ubuntu 20.04 without SGX.'),
                booleanParam(name: 'FULL_TEST_SUITE',       defaultValue: false,                     description: 'Run all additional tests available in the test suite.')
            ]
        )
    ]
)

try{
    def testing_stages = [
        "Check CI":                                { tests.checkCI() },
        "Check Developer Experience Ubuntu 20.04": { tests.checkDevFlows('20.04') },
        "Check Developer Experience Ubuntu 18.04": { tests.checkDevFlows('18.04') },
        "AArch64 2004 GNU gcc Debug":              { tests.AArch64GNUTest('20.04', 'Debug') },
        "AArch64 2004 GNU gcc RelWithDebInfo":     { tests.AArch64GNUTest('20.04', 'RelWithDebInfo') },
        "AArch64 1804 GNU gcc Debug":              { tests.AArch64GNUTest('18.04', 'Debug') },
        "AArch64 1804 GNU gcc RelWithDebInfo":     { tests.AArch64GNUTest('18.04', 'RelWithDebInfo') }
    ]
    if(FULL_TEST_SUITE == "true") {
        stage("Full Test Suite") {
            testing_stages += [
                "Sim 1804 clang-10 SGX1 Debug":                      { tests.simulationContainerTest('18.04', 'Debug',          ['-DHAS_QUOTE_PROVIDER=OFF', '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF']) },
                "Sim 1804 clang-10 SGX1 RelWithDebInfo":             { tests.simulationContainerTest('18.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=OFF', '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF']) },
                "Sim 1804 clang-10 SGX1FLC Debug":                   { tests.simulationContainerTest('18.04', 'Debug',          ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF']) },
                "Sim 1804 clang-10 SGX1FLC RelWithDebInfo":          { tests.simulationContainerTest('18.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF']) },
                "Sim 1804 clang-10 SGX1FLC Debug snmalloc":          { tests.simulationContainerTest('18.04', 'Debug',          ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF', '-DUSE_SNMALLOC=ON']) },
                "Sim 1804 clang-10 SGX1FLC RelWithDebInfo snmalloc": { tests.simulationContainerTest('18.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF', '-DUSE_SNMALLOC=ON']) },
                "Sim 2004 clang-10 SGX1 Debug":                      { tests.simulationContainerTest('20.04', 'Debug',          ['-DHAS_QUOTE_PROVIDER=OFF', '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF']) },
                "Sim 2004 clang-10 SGX1 RelWithDebInfo":             { tests.simulationContainerTest('20.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=OFF', '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF']) },
                "Sim 2004 clang-10 SGX1FLC Debug":                   { tests.simulationContainerTest('20.04', 'Debug',          ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF']) },
                "Sim 2004 clang-10 SGX1FLC RelWithDebInfo":          { tests.simulationContainerTest('20.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF']) },
                "Sim 2004 clang-10 SGX1FLC Debug snmalloc":          { tests.simulationContainerTest('20.04', 'Debug',          ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF', '-DUSE_SNMALLOC=ON']) },
                "Sim 2004 clang-10 SGX1FLC RelWithDebInfo snmalloc": { tests.simulationContainerTest('20.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=OFF', '-DUSE_SNMALLOC=ON']) },
                "Ubuntu 1804 Cross Platform Build":                  { tests.buildCrossPlatform("18.04") },
                "Ubuntu 2004 Cross Platform Build":                  { tests.buildCrossPlatform("20.04") }
            ]
            parallel testing_stages
        }
    } else {
        stage("PR Testing") {
            testing_stages += [
                "Sim 1804 clang-10 SGX1 RelWithDebInfo":             { tests.simulationContainerTest('18.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=OFF', '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=ON']) },
                "Sim 1804 clang-10 SGX1FLC Debug":                   { tests.simulationContainerTest('18.04', 'Debug',          ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=ON']) },
                "Sim 2004 clang-10 SGX1FLC RelWithDebInfo":          { tests.simulationContainerTest('20.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=ON']) },
                "Sim 2004 clang-10 SGX1FLC RelWithDebInfo snmalloc": { tests.simulationContainerTest('20.04', 'RelWithDebInfo', ['-DHAS_QUOTE_PROVIDER=ON',  '-DLVI_MITIGATION=None', '-DLVI_MITIGATION_SKIP_TESTS=ON', '-DUSE_SNMALLOC=ON']) },
                "Ubuntu 1804 Cross Platform Build":                  { tests.buildCrossPlatform("18.04") }
            ]
            parallel testing_stages
        }
    }
} catch(Exception e) {
    println "Caught global pipeline exception: " + e
    GLOBAL_ERROR = e
    throw e
} finally {
    currentBuild.result = (GLOBAL_ERROR != null) ? 'FAILURE' : "SUCCESS"
}
