// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_OE_T_H
#define EDGER8R_OE_T_H

#include <openenclave/enclave.h>
#include "oe_args.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

void public_root_ecall(void);

/* List of ocalls */

oe_result_t oe_hostfs_open(
    int* _retval,
    const char* pathname,
    int flags,
    mode_t mode,
    int* err);
oe_result_t oe_hostfs_read(
    ssize_t* _retval,
    int fd,
    void* buf,
    size_t count,
    int* err);
oe_result_t oe_hostfs_write(
    ssize_t* _retval,
    int fd,
    const void* buf,
    size_t count,
    int* err);
oe_result_t oe_hostfs_lseek(
    off_t* _retval,
    int fd,
    off_t offset,
    int whence,
    int* err);
oe_result_t oe_hostfs_close(int* _retval, int fd, int* err);
oe_result_t oe_hostfs_dup(int* _retval, int oldfd, int* err);
oe_result_t oe_hostfs_opendir(void** _retval, const char* name, int* err);
oe_result_t oe_hostfs_readdir(
    int* _retval,
    void* dirp,
    struct oe_hostfs_dirent_struct* ent,
    int* err);
oe_result_t oe_hostfs_rewinddir(void* dirp);
oe_result_t oe_hostfs_closedir(int* _retval, void* dirp, int* err);
oe_result_t oe_hostfs_stat(
    int* _retval,
    const char* pathname,
    struct oe_hostfs_stat_struct* buf,
    int* err);
oe_result_t oe_hostfs_access(
    int* _retval,
    const char* pathname,
    int mode,
    int* err);
oe_result_t oe_hostfs_link(
    int* _retval,
    const char* oldpath,
    const char* newpath,
    int* err);
oe_result_t oe_hostfs_unlink(int* _retval, const char* pathname, int* err);
oe_result_t oe_hostfs_rename(
    int* _retval,
    const char* oldpath,
    const char* newpath,
    int* err);
oe_result_t oe_hostfs_truncate(
    int* _retval,
    const char* path,
    off_t length,
    int* err);
oe_result_t oe_hostfs_mkdir(
    int* _retval,
    const char* pathname,
    mode_t mode,
    int* err);
oe_result_t oe_hostfs_rmdir(int* _retval, const char* pathname, int* err);

OE_EXTERNC_END

#endif // EDGER8R_OE_T_H
