// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_OE_U_H
#define EDGER8R_OE_U_H

#include <openenclave/host.h>
#include "oe_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_oe_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const void* config,
    uint32_t config_size,
    oe_enclave_t** enclave);

/* List of ecalls */

oe_result_t public_root_ecall(oe_enclave_t* enclave);

/* List of ocalls */

int oe_hostfs_open(const char* pathname, int flags, mode_t mode, int* err);
ssize_t oe_hostfs_read(int fd, void* buf, size_t count, int* err);
ssize_t oe_hostfs_write(int fd, const void* buf, size_t count, int* err);
off_t oe_hostfs_lseek(int fd, off_t offset, int whence, int* err);
int oe_hostfs_close(int fd, int* err);
int oe_hostfs_dup(int oldfd, int* err);
void* oe_hostfs_opendir(const char* name, int* err);
int oe_hostfs_readdir(
    void* dirp,
    struct oe_hostfs_dirent_struct* ent,
    int* err);
void oe_hostfs_rewinddir(void* dirp);
int oe_hostfs_closedir(void* dirp, int* err);
int oe_hostfs_stat(
    const char* pathname,
    struct oe_hostfs_stat_struct* buf,
    int* err);
int oe_hostfs_access(const char* pathname, int mode, int* err);
int oe_hostfs_link(const char* oldpath, const char* newpath, int* err);
int oe_hostfs_unlink(const char* pathname, int* err);
int oe_hostfs_rename(const char* oldpath, const char* newpath, int* err);
int oe_hostfs_truncate(const char* path, off_t length, int* err);
int oe_hostfs_mkdir(const char* pathname, mode_t mode, int* err);
int oe_hostfs_rmdir(const char* pathname, int* err);

OE_EXTERNC_END

#endif // EDGER8R_OE_U_H
