// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <openenclave/attestation/relying_party.h>
#include <openenclave/internal/cert.h>
#include <openenclave/internal/evidence.h>

#include "attest_plugin.h"
#include "common.h"
#include "tlsparser.h"

#define KEY_BUFF_SIZE 2048

static const char* _oid_oe_evidence_with_inittime_claims =
    X509_OID_FOR_OE_EVIDENCE_WITH_INITTIME_CLAIMS_STRING;
static const char* _oid_oe_attestation_result =
    X509_OID_FOR_ATTESTATION_RESULT_STRING;

/**
 * oe_parse_passport_attestation_certificate_v1
 *
 * This function parses the certificate generated by
 * oe_get_passport_attestation_certificate_v1 and outputs
 * the attestation result.
 *
 * @experimental
 *
 * @param[in] certificate_in_der A pointer to buffer holding certificate
 * contents in DER format.
 * @param[in] certificate_in_der_size The size of the buffer above.
 * @param[out] output_attestation_result_buffer A pointer to buffer
 * pointer.
 * @param[out] output_attestation_result_buffer_size A pointer to the
 * size of the buffer above.
 *
 * @retval OE_OK Successful parsing.
 * @retval OE_INVALID_PARAMETER One or more invalid parameters.
 * @retval Other appropriate error code.
 */
oe_result_t oe_parse_passport_attestation_certificate_v1(
    const uint8_t* certificate_in_der,
    size_t certificate_in_der_size,
    uint8_t** output_attestation_result_buffer,
    size_t* output_attestation_result_buffer_size)
{
    oe_result_t result = OE_FAILURE;
    oe_cert_t certificate = {0};
    uint8_t* attestation_result_buffer = NULL;
    size_t attestation_result_buffer_size = 0;

    if (!certificate_in_der || !certificate_in_der_size ||
        !output_attestation_result_buffer ||
        !output_attestation_result_buffer_size)
        OE_RAISE(OE_INVALID_PARAMETER);

    *output_attestation_result_buffer = NULL;
    *output_attestation_result_buffer_size = 0;

    result = oe_cert_read_der(
        &certificate, certificate_in_der, certificate_in_der_size);
    OE_CHECK_MSG(result, "certificate_in_der_size=%d", certificate_in_der_size);

    // Validate the certificate signature
    result = oe_cert_verify(&certificate, NULL, NULL, 0);
    OE_CHECK_MSG(
        result,
        "oe_cert_verify failed with error = %s\n",
        oe_result_str(result));

    result = oe_cert_find_extension(
        &certificate,
        (const char*)_oid_oe_attestation_result,
        &attestation_result_buffer,
        &attestation_result_buffer_size);
    OE_CHECK_MSG(
        result,
        "oe_cert_find_extension failed with error = %s\n",
        oe_result_str(result));

    *output_attestation_result_buffer = attestation_result_buffer;
    *output_attestation_result_buffer_size = attestation_result_buffer_size;

    result = OE_OK;

done:
    oe_cert_free(&certificate);
    return result;
}

/**
 * oe_parse_background_check_attestation_certificate_v1
 *
 * This function parses the certificate generated by
 * oe_get_background_check_attestation_certificate_v1
 * and outputs the evidence and optionally init-time custom
 * claims and run-time custom claims.
 *
 * @experimental
 *
 * @param[in] certificate_in_der A pointer to buffer holding certificate
 * contents in DER format.
 * @param[in] certificate_in_der_size The size of the buffer above.
 * @param[out] output_evidence_buffer A pointer to buffer pointer.
 * @param[out] output_evidence_buffer_size The size of the buffer above.
 * @param[out] output_inittime_custom_claims_buffer An optional pointer to
 * buffer pointer.
 * @param[out] output_inittime_custom_claims_buffer_size An optional pointer to
 * the size of the buffer above.
 * @param[out] output_runtime_custom_claims_buffer An optional pointer to buffer
 * pointer.
 * @param[out] output_runtime_custom_claims_buffer_size An optional pointer to
 * the size of the buffer above.
 *
 * @retval OE_OK Successful parsing.
 * @retval OE_INVALID_PARAMETER One or more invalid parameters.
 * @retval Other appropriate error code.
 */
oe_result_t oe_parse_background_check_attestation_certificate_v1(
    const uint8_t* certificate_in_der,
    size_t certificate_in_der_size,
    uint8_t** output_evidence_buffer,
    size_t* output_evidence_buffer_size,
    uint8_t** output_inittime_custom_claims_buffer,
    size_t* output_inittime_custom_claims_buffer_size,
    uint8_t** output_runtime_custom_claims_buffer,
    size_t* output_runtime_custom_claims_buffer_size)
{
    oe_result_t result = OE_FAILURE;
    oe_cert_t certificate = {0};
    uint8_t* evidence_with_inittime_claims = NULL;
    size_t evidence_with_inittime_claims_size = 0;

    if (!certificate_in_der_size || !certificate_in_der_size)
        OE_RAISE(OE_INVALID_PARAMETER);

    result = oe_cert_read_der(
        &certificate, certificate_in_der, certificate_in_der_size);
    OE_CHECK_MSG(result, "certificate_in_der_size=%d", certificate_in_der_size);

    // Validate the certificate signature
    result = oe_cert_verify(&certificate, NULL, NULL, 0);
    OE_CHECK_MSG(
        result,
        "oe_cert_verify failed with error = %s\n",
        oe_result_str(result));

    result = oe_cert_find_extension(
        &certificate,
        (const char*)_oid_oe_evidence_with_inittime_claims,
        &evidence_with_inittime_claims,
        &evidence_with_inittime_claims_size);
    OE_CHECK_MSG(
        result,
        "oe_cert_find_extension failed with error = %s\n",
        oe_result_str(result));

    OE_CHECK(oe_parse_evidence_with_inittime_claims(
        evidence_with_inittime_claims,
        evidence_with_inittime_claims_size,
        output_evidence_buffer,
        output_evidence_buffer_size,
        output_inittime_custom_claims_buffer,
        output_inittime_custom_claims_buffer_size,
        output_runtime_custom_claims_buffer,
        output_runtime_custom_claims_buffer_size));

    result = OE_OK;

done:
    oe_cert_free(&certificate);
    return result;
}
