// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#ifndef _TESTS_CRYPTO_EC_H
#define _TESTS_CRYPTO_EC_H

#include <openenclave/internal/ec.h>

/**
 * Get the key coordinates from an EC public key
 *
 * This function gets the key coordinates from an EC public key. The
 * coordinates are in uncompressed format.
 *
 * @param public_key key whose key bytes are fetched
 * @param x_data the buffer where the X-coordinate bytes are written
 * @param x_size[in,out] size of x_data buffer (in); size of data (out)
 * @param y_data the buffer where Y-coordinate bytes are written
 * @param y_size[in,out] size of y_data buffer (in); size of data (out)
 *
 * @return OE_OK upon success
 * @return OE_BUFFER_TOO_SMALL either the **x_data** or **y_data** are too small;
 *         **x_size** and **y_size** contain the required sizes.
 *
 */
oe_result_t oe_ec_public_key_to_coordinates(
    const oe_ec_public_key_t* public_key,
    uint8_t* x_data,
    size_t* x_size,
    uint8_t* y_data,
    size_t* y_size);

/**
 * Converts a DER-encoded signature into ECDSA signature values.
 *
 * This function converts a DER-encoded signature into binary-encoded ECDSA
 * signature values (r and s). DER-encoded signatures are generated by the
 * **oe_ec_private_key_sign()** function.
 *
 * @param signature the DER-encoded signature
 * @param signature_size the size of the signature
 * @param r_data the buffer that will contain the R coordinate.
 * @param r_size[in,out] size of r_data buffer (in); size of coordinate (out)
 * @param s_data the buffer that will contain the S coordinate.
 * @param s_size[in,out] size of s_data buffer (in); size of coordinate (out)
 *
 * @return OE_OK upon success
 * @return OE_INVALID_PARAMETER a parameter was invalid.
 * @return OE_BUFFER_TOO_SMALL either the **r_data** or **s_data** buffer is too
 *         small; **r_size** and **s_size** contain the required sizes on output.
 */
oe_result_t oe_ecdsa_signature_read_der(
    const uint8_t* signature,
    size_t signature_size,
    uint8_t* r_data,
    size_t* r_size,
    uint8_t* s_data,
    size_t* s_size);

#endif /* _TESTS_CRYPTO_EC_H */
