set(LIBUNWIND_C_SRC
    ${LIBUNWIND_SRC}/src/aarch64/Lstep.c
    ${LIBUNWIND_SRC}/src/aarch64/Ltrace.c
    ${LIBUNWIND_SRC}/src/dwarf/Gfind_proc_info-lsb.c
    ${LIBUNWIND_SRC}/src/dwarf/global.c
    ${LIBUNWIND_SRC}/src/dwarf/Lexpr.c
    ${LIBUNWIND_SRC}/src/dwarf/Lfde.c
    ${LIBUNWIND_SRC}/src/dwarf/Lfind_proc_info-lsb.c
    ${LIBUNWIND_SRC}/src/dwarf/Lfind_unwind_table.c
    ${LIBUNWIND_SRC}/src/dwarf/Lparser.c
    ${LIBUNWIND_SRC}/src/dwarf/Lpe.c
    #${LIBUNWIND_SRC}/src/dwarf/Lstep.c
    ${LIBUNWIND_SRC}/src/mi/_ReadULEB.c
    ${LIBUNWIND_SRC}/src/mi/_ReadSLEB.c
    ${LIBUNWIND_SRC}/src/mi/backtrace.c
    ${LIBUNWIND_SRC}/src/mi/dyn-cancel.c
    ${LIBUNWIND_SRC}/src/mi/dyn-info-list.c
    ${LIBUNWIND_SRC}/src/mi/dyn-register.c
    ${LIBUNWIND_SRC}/src/mi/flush_cache.c
    ${LIBUNWIND_SRC}/src/mi/init.c
    ${LIBUNWIND_SRC}/src/mi/Ldestroy_addr_space.c
    ${LIBUNWIND_SRC}/src/mi/Ldyn-extract.c
    ${LIBUNWIND_SRC}/src/mi/Lfind_dynamic_proc_info.c
    ${LIBUNWIND_SRC}/src/mi/Lget_accessors.c
    ${LIBUNWIND_SRC}/src/mi/Lget_fpreg.c
    ${LIBUNWIND_SRC}/src/mi/Lget_proc_info_by_ip.c
    ${LIBUNWIND_SRC}/src/mi/Lget_proc_name.c
    ${LIBUNWIND_SRC}/src/mi/Lget_reg.c
    ${LIBUNWIND_SRC}/src/mi/Lput_dynamic_unwind_info.c
    ${LIBUNWIND_SRC}/src/mi/Lset_caching_policy.c
    ${LIBUNWIND_SRC}/src/mi/Lset_fpreg.c
    ${LIBUNWIND_SRC}/src/mi/Lset_reg.c
    ${LIBUNWIND_SRC}/src/mi/mempool.c
    ${LIBUNWIND_SRC}/src/mi/strerror.c
    ${LIBUNWIND_SRC}/src/unwind/Backtrace.c
    ${LIBUNWIND_SRC}/src/unwind/DeleteException.c
    ${LIBUNWIND_SRC}/src/unwind/FindEnclosingFunction.c
    ${LIBUNWIND_SRC}/src/unwind/ForcedUnwind.c
    ${LIBUNWIND_SRC}/src/unwind/GetBSP.c
    ${LIBUNWIND_SRC}/src/unwind/GetCFA.c
    ${LIBUNWIND_SRC}/src/unwind/GetDataRelBase.c
    ${LIBUNWIND_SRC}/src/unwind/GetGR.c
    ${LIBUNWIND_SRC}/src/unwind/GetIPInfo.c
    ${LIBUNWIND_SRC}/src/unwind/GetIP.c
    ${LIBUNWIND_SRC}/src/unwind/GetLanguageSpecificData.c
    ${LIBUNWIND_SRC}/src/unwind/GetRegionStart.c
    ${LIBUNWIND_SRC}/src/unwind/GetTextRelBase.c
    ${LIBUNWIND_SRC}/src/unwind/RaiseException.c
    ${LIBUNWIND_SRC}/src/unwind/Resume.c
    ${LIBUNWIND_SRC}/src/unwind/Resume_or_Rethrow.c
    ${LIBUNWIND_SRC}/src/unwind/SetGR.c
    ${LIBUNWIND_SRC}/src/unwind/SetIP.c
    ${LIBUNWIND_SRC}/src/${ARCH}/getcontext.S
    ${LIBUNWIND_SRC}/src/${ARCH}/is_fpreg.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Lcreate_addr_space.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Lget_save_loc.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Lglobal.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Linit.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Lis_signal_frame.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Linit_local.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Linit_remote.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Lget_proc_info.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Lregs.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Lresume.c
    ${LIBUNWIND_SRC}/src/${ARCH}/Lstash_frame.c
    ${LIBUNWIND_SRC}/src/${ARCH}/regname.c
    ${LIBUNWIND_SRC}/src/os-linux.c
    ${LIBUNWIND_SRC}/src/elf64.c
)
set(LIBUNWIND_C_SRC ${LIBUNWIND_C_SRC} PARENT_SCOPE)
