#!/usr/bin/env bash

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

##==============================================================================
##
## This script performs various checks on the source tree in CI.
##
##==============================================================================

## Check whether source code has been formatted (diff outputs '@@'):
if ./scripts/format-code --whatif | grep -q "@@"; then
    echo ""
    echo "Commit failed: please run ./scripts/format-code"
    echo ""
    exit 1
fi

# Check whether all sources have the license header:
if ! ./scripts/check-license; then
    echo ""
    echo "Commit failed: please add license headers to the above files"
    echo ""
    exit 1
fi

# Check whether all scripts pass ShellCheck:
if ! ./scripts/check-linters; then
    echo ""
    echo "Commit failed: please run ./scripts/check-linters"
    echo ""
    exit 1
fi
