#!/usr/bin/env bash

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

##==============================================================================
##
## This script performs various checks on the source tree. If any of these fail
## commits fail.
##
##==============================================================================

## Check whether source code has been formatted:
./scripts/format-code --whatif | grep -q "@@"
if [ "$?" == "0" ]; then
    echo ""
    echo "Commit failed: please run ./scripts/format-code"
    echo ""
    exit 1
fi

# Check whether all sources have the license header:
./scripts/check-license
if [ "$?" != "0" ]; then
    echo ""
    echo "Commit failed: please add license headers to the above files"
    echo ""
    exit 1
fi
