#!/bin/bash

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

##==============================================================================
##
## check-license:
##
##     This script checks for Open Enclave files that are missing the license
##     header. It prints the names of files with missing headers to standard
##     output.
##
##     To ignore certain files or directories, add them to:
##         .check-license.ignore
##
##==============================================================================

##==============================================================================
##
## Check command line arguments.
##
##==============================================================================

if [ "$#" != "0" ]; then
    echo "$0: too many parameters"
    echo "Usage: $0"
    exit 1
fi

##==============================================================================
##
## expand_ignore_file():
##
##     Expand any wildcards in the .check-license.ignore file:
##
##==============================================================================

expand_ignore_file()
{
    local filename=".check-license.ignore"
    local tempfile=`/bin/mktemp`

    # Create empty ignore file:
    touch ${tempfile}

    # Fail if ignore file does not exist:
    if [ -f "${filename}" ]; then
        # Expand each entry in the ignore file:
        set -f
        for i in `cat ${filename}`
        do
            bn=`basename ${i}`
            if [ "${bn}" == "${i}" ]; then
                find . -name "${bn}" >> ${tempfile}
            else
                if [ -e "${i}" ]; then
                    echo ${i} >> ${tempfile}
                else
                    set +f
                    ls -1 ${i} >> ${tempfile} 2> /dev/null
                    set -f
                fi
            fi
        done
        set +f
    fi

    echo ${tempfile}
}

ignorefile=`expand_ignore_file`

##==============================================================================
##
## form_filelist(ignorefile):
##
##     Form the list of files by finding all regular files and then removing
##     ignore files.
##
##==============================================================================

form_filelist()
{
    local ignorefile=$1
    local files=`/bin/mktemp`
    local tmpfile=`/bin/mktemp`

    # Find all regular files:
    find . -type f >> ${files}

    # Remove lines that match entries from ignore file:
    for i in `cat ${ignorefile}`
    do
        cp ${files} ${tmpfile}

        if [ -d "${i}" ]; then
            grep -v "${i}/" ${tmpfile} > ${files}
        else
            grep -v "^${i}\$" ${tmpfile} > ${files}
        fi
    done

    rm -f ${tmpfile}

    echo ${files}
}

filelist=`form_filelist ${ignorefile}`
rm -rf ${ignorefile}

# Sanity check: make sure all files that require licenses exist
while read -u 99 i; do
    if [ ! -f "${i}" ]; then
        echo "Iterating through ${filelist}: file not found: ${i}"
        rm -f ${filelist}
        exit 1
    fi
done 99<${filelist}

##==============================================================================
##
## Write the license header to a temporary file.
##
##==============================================================================

license=`/bin/mktemp`

cat > ${license} <<EOF
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License.
EOF

##==============================================================================
##
## check_for_missing_license_headers(filelist, license)
##
##     Check each Open Enclave files that are missing the license header.
##
##==============================================================================

function check_for_missing_license_headers()
{
    local filelist="$1"
    local license="$2"
    local tmpfile=`/bin/mktemp`
    local ret=0

    while read -u 99 i; do
        # Grep for first 'Copyright' line (-m1)
        # Print the following line too (-A1)
        # Use SED to strip leading '//' or leading '#':
        grep -m1 -A1 "Copyright (c) Microsoft Corporation" "${i}" | \
        sed 's~// ~~g' | \
        sed 's~;; ~~g' | \
        sed 's~:: ~~g' | \
        sed 's~^# ~~g' \
        > ${tmpfile}

        # Diff matching file with expected license text:
        diff -w ${tmpfile} ${license} > /dev/null 2> /dev/null
        if [ "$?" != "0" ]; then
            echo ${i}
            ret=1
        fi
    done 99<${filelist}

    rm -rf ${tmpfile}
    rm -f ${filelist}

    return ${ret}
}

check_for_missing_license_headers "${filelist}" "${license}"
