#!/bin/bash

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

##==============================================================================
##
## check-license:
##
##     This script checks for OpenEnclave files that are missing the license
##     header. It prints the names of files with missing headers to standard
##     output.
##
##     To ignore certain files or directories, add them to:
##         ./scripts/.check-license.ignore
##
##==============================================================================

##==============================================================================
##
## Check command line arguments.
##
##==============================================================================

if [ "$#" != "0" ]; then
    echo "$0: too many parameters"
    echo "Usage: $0"
    exit 1
fi

##==============================================================================
##
## check_directory()
##
##     Check that script is running from the root of the openenclave 
##     distribution.
##
##==============================================================================

check_directory()
{
    if [ "`basename ${PWD}`" != "openenclave" ]; then
        echo "$0: please run from root of openenclave source tree"
        exit 1
    fi
}

check_directory

##==============================================================================
##
## expand_ignore_file():
##
##     Expand any wildcards in the .check-license.ignore file:
##
##==============================================================================

expand_ignore_file()
{
    local filename="./scripts/.check-license.ignore"
    local tempfile=`/bin/mktemp`

    # Fail if ignore file does not exist:
    if [ ! -f "${filename}" ]; then
        echo "$0: missing file: ${filename}"
        exit 1
    fi

    # Expand each entry in the ignore file:
    set -f
    for i in `cat ${filename}`
    do
        if [ -e "${i}" ]; then
            echo ${i} >> ${tempfile}
        else
            bn=`basename ${i}`
            if [ "${bn}" == "${i}" ]; then
                find . -name "${bn}" >> ${tempfile}
            else
                set +f
                echo ${i} >> ${tempfile}
                set -f
            fi
        fi
    done
    set +f

    echo ${tempfile}
}

ignorefile=`expand_ignore_file`

##==============================================================================
##
## form_filelist(ignorefile):
##
##     Form the list of files by finding all regular files and then removing
##     ignore files.
##
##==============================================================================

form_filelist()
{
    local ignorefile=$1
    local files=`/bin/mktemp`
    local tmpfile=`/bin/mktemp`

    # Find all regular files:
    find . -type f >> ${files}

    # Remove lines that match entries from ignore file:
    for i in `cat ${ignorefile}`
    do
        cp ${files} ${tmpfile}
        fgrep -v ${i} ${tmpfile} > ${files}
    done

    filelist=`cat ${files}`

    rm -f ${files}
    rm -f ${tmpfile}

    # Sanity check: make sure all files in list exist:
    for i in ${filelist}
    do 
        if [ ! -f "${i}" ]; then
            echo "$0: file not found: ${i}"
            exit 1
        fi
    done

    echo ${filelist}
}

filelist=`form_filelist ${ignorefile}`
rm -rf ${ignorefile}

##==============================================================================
##
## check_not_included():
##
##     Find files that are not included but that have Microsoft license.
##
##==============================================================================

check_not_included()
{
    tmpfile1=`/bin/mktemp`
    ls ${filelist} | sed 's/^..//g' | sort >> ${tmpfile1}

    tmpfile2=`/bin/mktemp`
    grep -r -l 'Copyright (c) Microsoft Corporation' | sort >> ${tmpfile2}

    echo diff ${tmpfile1} ${tmpfile2}
    diff ${tmpfile1} ${tmpfile2}

    rm -f ${tmpfile1}
    rm -f ${tmpfile2}
}

##==============================================================================
##
## Write the license header to a temporary file.
##
##==============================================================================

license=`/bin/mktemp`

cat > ${license} <<EOF
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License.
EOF

##==============================================================================
##
## check_for_missing_license_headers(filelist, license)
##
##     Check each OpenEnclave files that are missing the license header.
##
##==============================================================================

function check_for_missing_license_headers()
{
    local filelist="$1"
    local license="$2"
    local tmpfile=`/bin/mktemp`
    local ret=0

    for i in ${filelist}
    do
        # Grep for first 'Copyright' line (-m1)
        # Print the following line too (-A1)
        # Use SED to strip leading '//' or leading '#':
        grep -m1 -A1 "Copyright (c) Microsoft Corporation" ${i} | \
        sed 's~// ~~g' | \
        sed 's~;; ~~g' | \
        sed 's~^# ~~g' \
        > ${tmpfile}

        # Diff matching file with expected license text:
        diff -w ${tmpfile} ${license} > /dev/null 2> /dev/null
        if [ "$?" != "0" ]; then
            echo ${i}
            ret=1
        fi
    done

    rm -rf ${tmpfile}

    return ${ret}
}

check_for_missing_license_headers "${filelist}" "${license}"
