#!/bin/bash

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

##==============================================================================
##
## check-license:
##
##     This script checks for OpenEnclave sources that are missing the license
##     header. It prints the names of files with missing headers to standard
##     output.
##
##     To ignore certain sources from this check, add them to:
##         ./scripts/.check-license.ignore
##
##==============================================================================

##==============================================================================
##
## Reject any parameters.
##
##==============================================================================

if [ "$#" != "0" ]; then
    echo "$0: too many parameters"
    echo "Usage: $0"
    exit 1
fi

##==============================================================================
##
## The script must be run from the root of the openenclave source tree.
##
##==============================================================================

bn=`basename ${PWD}`

if [ "${bn}" != "openenclave" ]; then
    echo "$0: please run from root of openenclave source tree"
    exit 1
fi

##==============================================================================
##
## Form the list of files to ignore from the test below.
##
##==============================================================================

ignorefile="./scripts/.check-license.ignore"

if [ ! -f "${ignorefile}" ]; then
    echo "$0: missing file: ${ignorefile}"
    exit 1
fi

ignorelist=`cat ${ignorefile}`

##==============================================================================
##
## Form the list of files to include from the test below.
##
##==============================================================================

includefile="./scripts/.check-license.include"

if [ ! -f "${includefile}" ]; then
    echo "$0: missing file: ${includefile}"
    exit 1
fi

##==============================================================================
##
## Form the list of all OpenEnclave files.
##
##==============================================================================

files=`/bin/mktemp`

find . -name '*.h' >> ${files}
find . -name '*.c' >> ${files}
find . -name '*.cpp' >> ${files}
find . -name '*.asm' >> ${files}
find . -name '*.S' >> ${files}
find . -name '*.conf' >> ${files}
find . -name '*.idl' >> ${files}
find . -name '*.inc' >> ${files}
find . -name '*.cmake' >> ${files}
find . -name 'CMakeLists.txt' >> ${files}
find . -name 'Makefile' >> ${files}
find . -name '*.make' >> ${files}
find . -name '*.py' >> ${files}
grep '#[ \t]*!.*bash' -r -l . >> ${files}

# Append include file to files:
cat ${includefile} >> ${files}

tmpfile=`/bin/mktemp`

# Remove lines that match entries from ignore file:
for i in ${ignorelist}
do
    cp ${files} ${tmpfile}
    fgrep -v ${i} ${tmpfile} > ${files}
done

fileslist=`cat ${files}`

rm -f ${tmpfile}

##==============================================================================
##
## Verify that ${fileslist} was properly formed (check that each file exists)
##
##==============================================================================

for i in ${fileslist}
do 
    if [ ! -f "${i}" ]; then
        echo "$0: file not found: ${i}"
        exit 1
    fi
done

##==============================================================================
##
## Find files that are not included but that have Microsoft license:
##
##==============================================================================

function check_not_included()
{
    tmpfile1=`/bin/mktemp`
    ls ${fileslist} | sed 's/^..//g' | sort >> ${tmpfile1}

    tmpfile2=`/bin/mktemp`
    grep -r -l 'Copyright (c) Microsoft Corporation' | sort >> ${tmpfile2}

    echo diff ${tmpfile1} ${tmpfile2}
    diff ${tmpfile1} ${tmpfile2}

    exit
}

##==============================================================================
##
## Write the license header to a temporary file.
##
##==============================================================================

license=`/bin/mktemp`

cat > ${license} <<EOF
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License.
EOF

##==============================================================================
##
## Check each openenclave source file for the license.
##
##==============================================================================

tmpfile=`/bin/mktemp`

success=0

for i in ${fileslist}
do
    # Grep for first 'Copyright' line (-m1)
    # Print the following line too (-A1)
    # Use SED to strip leading '//' or leading '#':
    grep -m1 -A1 "Copyright (c) Microsoft Corporation" ${i} | \
    sed 's~// ~~g' | \
    sed 's~;; ~~g' | \
    sed 's~^# ~~g' \
    > ${tmpfile}

    # Diff matching file with expected license text:
    diff -w ${tmpfile} ${license} > /dev/null 2> /dev/null
    if [ "$?" != "0" ]; then
        echo ${i}
        success=1
    fi
done

##==============================================================================
##
## Cleanup temporary files and print exit
##
##==============================================================================

rm -f ${tmpfile} ${license} ${files}
exit ${success}
