#!/bin/bash

##==============================================================================
##
## cxx-check:
##
##     This script is a wrapper for running GCC, but it first runs G++ to catch
##     potential problems that might not be caught by the C compiler.
##
##==============================================================================

prog=$0

##
## Check usage:
##

if [ "$1" == "" ]; then
    echo "$0: missing arguments"
    exit 1
fi

##
## Get the root of the source tree.
##

root=`dirname ${prog}`
root=`dirname ${root}`

##
## Remove C-only options and find C source file if any.
##

cc=$1
shift

args=
src=

for i
do
    skip=0

    if [ "${i}" == "-Wjump-misses-init" ]; then
        skip=1
    fi

    if [ "${i}" == "-Wmissing-prototypes" ]; then
        skip=1
    fi

    if [ "${i}" == "-Wno-pointer-sign" ]; then
        skip=1
    fi

    if [ "${i}" == "-std=c99" ]; then
        skip=1
    fi

    if [ "${i}" == "-fexcess-precision=standard" ]; then
        skip=1
    fi

    if [ "${i}" == "-Wstrict-prototypes" ]; then
        skip=1
    fi

    if [ -f "${i}" ]; then

        case "${i}" in
            *.c)
                src=`readlink -e ${i}`
                ;;
        esac
    fi

    if [ "${skip}" != "1" ]; then
        args+=${i}
        args+=" "
    fi
done

##
## Ignore C source file if its on the ignore list.
##

ignore=${root}/.cxx-check.ignore

#echo "=== SRC=${src}"

if [ -f "${src}" ]; then

    if [ -f "${ignore}" ]; then

        for i in `cat ${ignore}`
        do

            dir=`(cd ${root}; readlink -e "${i}")`

            if [ -d "${f}" ]; then
                echo "${prog}: not a directory: ${dir}"
                exit 1
            fi

            #echo "===DIR=${dir}"

            case "${src}" in
                ${dir}/*)
                    src=
                    ;;
            esac

        done

    fi

fi

##
## If a C source file was found and not ignored then compile C++:
##
if [ "${src}" != "" ]; then

cat<<EOF
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
EOF
    g++ ${args}
    if [ "$?" != "0" ]; then
        exit 1
    fi

fi

##
## Now compile with C:
##
${cc} ${args}
if [ "$?" != "0" ]; then
    exit 1
fi
