#!/bin/bash

##==============================================================================
##
## Check usage:
##
##==============================================================================

if [ "$#" != "0" ]; then
    echo "Usage: $0"
    exit 1
fi

echo

##==============================================================================
##
## Fail if not in the OpenEnclave root directory:
##
##==============================================================================

if [ ! -f ".openenclaveroot" ]; then
    echo "$0: must be run from root of OpenEnclave directory"
    exit 1
fi

##==============================================================================
##
## Source in .config file:
##
##==============================================================================

if [ ! -f ".config" ]; then
    echo "$0: missing .config file"
    exit 1
fi

source .config

##==============================================================================
##
## Check for presence of variables defined in .config
##
##==============================================================================

if [ -z "${OE_DISTRONAME}" ]; then
    echo "$0: OE_DISTRONAME undefined"
    exit 1
fi

if [ -z "${OE_MAJOR}" ]; then
    echo "$0: OE_MAJOR undefined"
    exit 1
fi

if [ -z "${OE_MINOR}" ]; then
    echo "$0: OE_MINOR undefined"
    exit 1
fi

if [ -z "${OE_REVISION}" ]; then
    echo "$0: OE_REVISION undefined"
    exit 1
fi

if [ -z "${OE_VERSION}" ]; then
    echo "$0: OE_VERSION undefined"
    exit 1
fi

if [ -z "${OE_PREFIX}" ]; then
    echo "$0: OE_PREFIX undefined"
    exit 1
fi

if [ -z "${OE_LIBDIR}" ]; then
    echo "$0: OE_LIBDIR undefined"
    exit 1
fi

if [ -z "${OE_BINDIR}" ]; then
    echo "$0: OE_BINDIR undefined"
    exit 1
fi

if [ -z "${OE_INCLUDEDIR}" ]; then
    echo "$0: OE_INCLUDEDIR undefined"
    exit 1
fi

##==============================================================================
##
## Install libraries: ${OE_LIBDIR}/openenclave
##
##==============================================================================

mkdir -p ${OE_LIBDIR}

if [ ! -d "${OE_LIBDIR}" ]; then
    echo "$0: failed to create ${OE_LIBDIR}"
    exit 1
fi

rm -rf ${OE_LIBDIR}/openenclave
cp -r lib ${OE_LIBDIR}/openenclave
rm -rf ${OE_LIBDIR}/openenclave/tmp

echo "Created ${OE_LIBDIR}/openenclave"

##==============================================================================
##
## Install programs: ${OE_BINDIR}/openenclave
##
##==============================================================================

BINDIR=${OE_BINDIR}/openenclave

rm -rf ${BINDIR}
mkdir -p ${BINDIR}

if [ ! -d "${BINDIR}" ]; then
    echo "$0: failed to create ${BINDIR}"
    exit 1
fi

cp bin/oesign ${BINDIR}
if [ ! -x "${BINDIR}/oesign" ]; then
    echo "$0: failed to install ${BINDIR}/oesign"
    exit 1
fi

cp bin/oegen ${BINDIR}
if [ ! -x "${BINDIR}/oegen" ]; then
    echo "$0: failed to install ${OE_BINDIR}/oegen"
    exit 1
fi

echo "Created ${BINDIR}"

##==============================================================================
##
## Install includes: ${OE_INCLUDEDIR}/openenclave
##
##==============================================================================

mkdir -p ${OE_INCLUDEDIR}

if [ ! -d "${OE_INCLUDEDIR}" ]; then
    echo "$0: failed to create ${OE_INCLUDEDIR}"
    exit 1
fi

INCLUDEDIR=${OE_INCLUDEDIR}/openenclave

rm -rf ${INCLUDEDIR}
cp -r include ${INCLUDEDIR}

echo "Created ${INCLUDEDIR}"

##==============================================================================
##
## Create the data directory: ${OE_DATADIR}/openenclave
##
##==============================================================================

DATADIR=${OE_DATADIR}/openenclave
rm -rf ${DATADIR}
mkdir -p ${DATADIR}

if [ ! -d "${DATADIR}" ]; then
    echo "$0: failed to create ${DATADIR}"
    exit 1
fi

echo "Created ${DATADIR}"

##==============================================================================
##
## Install enclave.mak
##
##==============================================================================

ENCLAVEMAK=${DATADIR}/enclave.mak
TEMPLATE=./scripts/enclave.mak.template

if [ ! -f "${TEMPLATE}" ]; then
    echo "$0: missing file: ${TEMPLATE}"
    exit 1
fi

rm -f ${ENCLAVEMAK}
cat .config >> ${ENCLAVEMAK}
cat ${TEMPLATE} >> ${ENCLAVEMAK}

if [ ! -f "${ENCLAVEMAK}" ]; then
    echo "$0: failed to create ${ENCLAVEMAK}" 
    exit 1
fi

echo "Created ${ENCLAVEMAK}"

##==============================================================================
##
## Install host.mak
##
##==============================================================================

HOSTMAK=${DATADIR}/host.mak

rm -f ${HOSTMAK}
cat .config >> ${HOSTMAK}

if [ ! -f "${HOSTMAK}" ]; then
    echo "$0: failed to create ${HOSTMAK}" 
    exit 1
fi

echo "Created ${HOSTMAK}"

##==============================================================================
##
## Install samples
##
##==============================================================================

SAMPLESDIR=${DATADIR}/samples
rm -f ${SAMPLEDIR}

cp -r samples ${SAMPLESDIR}

if [ ! -d "${SAMPLESDIR}" ]; then
    echo "$0: failed to create ${SAMPLESDIR}" 
    exit 1
fi

echo "Created ${SAMPLESDIR}"

##==============================================================================
##
## Install environment
##
##==============================================================================

ENVIRONMENT=${DATADIR}/environment

rm -rf ${ENVIRONMENT}
echo "export OPENENCLAVE_DATADIR=${DATADIR}" >> ${ENVIRONMENT}
echo "export PATH=\${PATH}:${BINDIR}" >> ${ENVIRONMENT}

if [ ! -f "${ENVIRONMENT}" ]; then
    echo "$0: failed to create ${ENVIRONMENT}"
    exit 1
fi

echo "Created ${ENVIRONMENT}"

echo
echo "Source ${ENVIRONMENT} to initialize the OpenEnclave environment"
echo
