#!/bin/bash

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Install required packages.
#
# When using new tools, obtain the corresponding package they come from with
# dpkg -S <binary-name>
# and add it to the list.
#

# Needed for Open Enclave build and scripts
PACKAGES="clang-format cmake gcc g++ make"

# Needed for using oedbg
PACKAGES="$PACKAGES gdb"

# Needed for 3rdparty/libunwind
PACKAGES="$PACKAGES autoconf libtool"

# Needed to generate documentation during make
PACKAGES="$PACKAGES doxygen graphviz"

# Needed for cmake/get_c_compiler_dir.sh
PACKAGES="$PACKAGES gawk"

# Needed for dox2md document generation
PACKAGES="$PACKAGES libexpat1-dev"

# Needed for oesign
PACKAGES="$PACKAGES openssl"

# Needed for oehost
PACKAGES="$PACKAGES libssl-dev"

# Needed for 3rdparty/libcxx/update.make
PACKAGES="$PACKAGES subversion"

# Needed for oeedger8r
PACKAGES="$PACKAGES ocaml-native-compilers"

apt-get -y install $PACKAGES
