#!/usr/bin/env bash
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# llvm-arw is a wrapper over llvm-ar. It converts Windows style 
# directory separator (\) to Linux style directory separator (/) 
# in any response files.

function call_llvmar {
    args=()

    # Transform any response file.
    for a; do
        # Response files start with an @
        if [[ "$a" == \@* ]]; then
            # Transform directory separators within the response file.
            sed -i 's/\\/\//g' "${a:1}"
        fi

        args+=("$a ")
    done

    # Replace \ by / in each argument
    args+=("$a ")
    llvm-ar "${args[@]}"
}

call_llvmar "$@"
