#!/bin/bash

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

cflags=$(pkg-config oeenclave-g++ --cflags)
libs=$(pkg-config oeenclave-g++ --libs)
/usr/bin/g++ "$@" ${cflags} ${libs}
