#!/bin/bash

set -o errexit
set -o pipefail

scripts=$(git rev-parse --show-toplevel)/scripts
files=($(git diff --cached --name-only))

if "$scripts/format-code" --whatif --files="${files[*]}" | grep -q "@@"; then
    echo "Commit failed: please run './scripts/format-code' to fix the formatting"
    exit 1
fi

if ! "$scripts/check-license" "${files[@]}"; then
    echo "Commit failed: please add license headers to the above files"
    exit 1
fi

if ! "$scripts/check-linters" "${files[@]}"; then
    echo "Commit failed: please run './scripts/check-linters' and fix the warnings"
    exit 1
fi

if ! git diff-index --check --cached HEAD --; then
    echo "Commit failed: please fix the conflict markers or whitespace errors"
    exit 1
fi
