T(RN,             nan,             nan,          0x0p+0, 0)
T(RN,             inf,             inf,          0x0p+0, 0)
T(RN,          0x1p+0,          0x0p+0,          0x0p+0, 0)
T(RN,     0x1.ffffp-1,             nan,          0x0p+0, INVALID)
T(RN,          0x0p+0,             nan,          0x0p+0, INVALID)
T(RN,         -0x0p+0,             nan,          0x0p+0, INVALID)
T(RN,            -inf,             nan,          0x0p+0, INVALID)
T(RN,        -0x1p+50,             nan,          0x0p+0, INVALID)
