T(RN,                  0x0p+0,                  0x0p+0,          0x0p+0, 0)
T(RN,                 -0x0p+0,                 -0x0p+0,          0x0p+0, 0)
T(RN,                     inf,                     inf,          0x0p+0, 0)
T(RN,                    -inf,                    -inf,          0x0p+0, 0)
T(RN,                     nan,                     nan,          0x0p+0, 0)
