# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include distribution vars
  include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- name: Include distribution release specific vars
  include_vars:
    file: "{{ ansible_distribution_release | lower }}.yml"

- name: Check for existing required files
  stat:
    path: "{{ item }}"
  with_items: "{{ packages_validation_files }}"
  register: file
  failed_when: file.stat.exists == False
