# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include distribution vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Add Microsoft Repository
  ansible.builtin.include_role:
    name: linux/common
    tasks_from: apt-repo.yml
  vars:
    apt_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    apt_repository: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"

- name: Install the official Azure-DCAP-Client APT package
  ansible.builtin.apt:
    name: "az-dcap-client={{ az_dcap_client_version }}"
    state: present
    update_cache: yes
