# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Install docker prerequisite packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  apt:
    name: [
      automake,
      dh-exec,
      dpkg-dev,
      gawk,
      git,
      libcurl3,
      libmbedtls10,
      libprotobuf9v5,
      sudo
    ]
    state: present
    update_cache: yes
    install_recommends: no

- name: Install docker prerequisite packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  apt:
    name: [
      automake,
      dh-exec,
      dpkg-dev,
      gawk,
      git,
      libcurl4,
      libmbedtls10,
      libprotobuf10,
      sudo
    ]
    state: present
    update_cache: yes
    install_recommends: no

# Workaround for Ubuntu 18.04 docker image
# https://github.com/intel/linux-sgx/blob/master/linux/installer/common/psw/install.sh#L66-L99
- name: Creates /etc/init directory
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  file:
    path: /etc/init
    state: directory
