/* Copyright (c) Microsoft Corporation. All rights reserved. */
/* Licensed under the MIT License. */
#pragma once

#define TCPS_LOG_DEV    0x0

#define TCPS_LOG_SVC    0x10000

#define TCPS_LOG_OTS    (TCPS_LOG_SVC + 0x0)
#define TCPS_LOG_RM     (TCPS_LOG_SVC + 0x2000)
#define TCPS_LOG_LA     (TCPS_LOG_SVC + 0x4000)


typedef enum _TCPS_LOG_ID {
    TCPS_LOG_DEV_PROVISIONING_STARTED = TCPS_LOG_DEV,
    TCPS_LOG_DEV_PROVISIONING_COMPLETED,
    TCPS_LOG_DEV_FAILURE,

    TCPS_LOG_OTS_INCOMING_CONNECTION = TCPS_LOG_OTS,
    TCPS_LOG_OTS_PROVISIONING_STARTED,
    TCPS_LOG_OTS_PROVISIONING_COMPLETED,
    TCPS_LOG_OTS_PROVISIONING_FAILED,

    TCPS_LOG_RM_INCOMING_CONNECTION = TCPS_LOG_RM,
    TCPS_LOG_RM_PROVISIONING_STARTED,
    TCPS_LOG_RM_PROVISIONING_COMPLETED,
    TCPS_LOG_RM_PROVISIONING_FAILED,

    TCPS_LOG_LA_LOG_BREAK_DETECTED = TCPS_LOG_LA,
    TCPS_LOG_LA_LOG_BAD_DETECTED
} TCPS_LOG_ID;
