// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#ifndef _CONTEXT_H
#define _CONTEXT_H

#ifndef __ASSEMBLER__
#include <openenclave/defs.h>
#include <openenclave/types.h>
#include "sgxtypes.h"

OE_CHECK_SIZE(sizeof(OE_CONTEXT), OE_CONTEXT_SIZE);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, flags), OE_CONTEXT_FLAGS);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rax), OE_CONTEXT_RAX);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rbx), OE_CONTEXT_RBX);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rcx), OE_CONTEXT_RCX);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rdx), OE_CONTEXT_RDX);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rbp), OE_CONTEXT_RBP);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rsp), OE_CONTEXT_RSP);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rdi), OE_CONTEXT_RDI);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rsi), OE_CONTEXT_RSI);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, r8), OE_CONTEXT_R8);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, r9), OE_CONTEXT_R9);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, r10), OE_CONTEXT_R10);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, r11), OE_CONTEXT_R11);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, r12), OE_CONTEXT_R12);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, r13), OE_CONTEXT_R13);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, r14), OE_CONTEXT_R14);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, r15), OE_CONTEXT_R15);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, rip), OE_CONTEXT_RIP);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, mxcsr), OE_CONTEXT_MXCSR);
OE_CHECK_SIZE(OE_OFFSETOF(OE_CONTEXT, basic_xstate), OE_CONTEXT_FLOAT);

void OE_SnapCurrentContext(OE_CONTEXT* oe_context);
void OE_RestorePartialContext(OE_CONTEXT* oe_context);
void OE_ContinueExecution(OE_CONTEXT* oe_context);

#endif // !__ASSEMBLER__

#endif /* _CONTEXT_H */
