verbatim "types.h"

struct EmptyStruct
{
};

struct MyStruct
{
    uint32 x;
    [count=size] const void* data;
    size_t size;
    [string] const char* str;
};

struct DeepStruct
{
    [count=1] struct MyStruct* flat;
    struct MyStruct mine[3];
};

struct MyObject
{
    uint32 id;
    [string] const char* name;
};

struct EmbeddedMyObject
{
    struct MyObject object1[1];
    struct MyObject object4[4];
    [count=1] struct MyObject* object;
    struct MyObject object0[];
};

struct ListElem
{
    [count=1] struct ListElem* prev;
    [count=1] struct ListElem* next;
    [string] const char* name;
};
struct Object
{
    size_t id;
    [string] char* name;
};

struct Embedded
{
    uint32 xxx;
    uint32 yyy;
    char str[16];
    [string] char cstr[16];
    [string] wchar wstr[16];
    [count=nobjects] struct Object* objects;
    size_t nobjects;
};

struct Container
{
    [count=size] struct Object* object;
    size_t size;
    bool b;
    struct Embedded e;
    struct Embedded ae[2];
    [count=arrSize] uint32* arrData;
    size_t arrSize;
    [unchecked] struct DefinedStruct definedStruct;
    [unchecked] struct UndefinedStruct* undefinedStruct;

    // unimplemented [count=size] const char* strings[2];
    //size numStrings;

    [count=sizevarr] const void* varr;
    size_t sizevarr;
};

struct AllTypes
{
    sint8 s8;
    uint8 u8;
    sint16 s16;
    uint16 u16;
    sint32 s32;
    uint32 u32;
    sint64 s64;
    uint64 u64;
    float r32;
    double r64;
    uint8 by;
    bool b;
    char c;
    wchar w;
    size_t s;
    ssize_t ss;
    [string, count=strn] char* str;
    size_t strn;
    [string] wchar* wcs;
    [string] char stra[32];
    [string] wchar wcsa[32];
    struct Object obj1;
    [count=1] struct Object* obj2;
    [count=size] uint32* data;
    size_t size;
};

struct NewTypes
{
    char s8;
    uint8 u8;
    short s16;
    uint16 u16;
    int s32;
    unsigned int u32;
    sint64 s64;
    uint64 u64;
    float r32;
    double r64;
    sint64 ss;
    uint64 s;
    signed long sl;
    unsigned int ui;
    unsigned long ul;
    [unchecked] unsigned short* usp;
    unsigned char uc;
};

struct MyFunctionArgs
{
    [string, in] const char* cstr;
    [string, out, count=nstr] char* str;
    size_t nstr;
    [out, count=1] uint32* u32;
    [out] uint32 u32a[4];
    [string, out] char stra[32];
    [in] struct Object obj;
    [in, out, count=1] struct Object* objp;
    [in, out, count=1] struct Object* objr;
};

function [ocall] sint32 UCopy(
    [out, count=m] char* p, 
    [in] size_t m,
    [in, count=n] const char* q, 
    [in] size_t n,
    [out, ref, count=1] struct Object* object);

function [ecall] sint32 TCopy(
    [out, count=m] char* p, 
    [in] size_t m,
    [in, count=n] const char* q, 
    [in] size_t n,
    [out, ref, count=1] struct Object* object);

