// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

function [ecall] void Ping(
    [in, string] const char* in,
    [in, out, string] char out[128]);

function [ocall] void Pong(
    [in, string] const char* in,
    [in, out, string] char out[128]);

function [ocall] void Log(
    [string, in] const char* str,
    [in] uint64 x);
