// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

OECI_LIB_VERSION = env.OECI_LIB_VERSION ?: "master"
oe = library("OpenEnclaveCommon@${OECI_LIB_VERSION}").jenkins.common.Openenclave.new()

GLOBAL_TIMEOUT_MINUTES = 240
CTEST_TIMEOUT_SECONDS = 1200
GLOBAL_ERROR = null

DOCKER_TAG = env.DOCKER_TAG ?: "latest"
AGENTS_LABELS = [
    "ubuntu-nonsgx":    env.UBUNTU_NONSGX_CUSTOM_LABEL ?: "nonSGX",
    "acc-win2016":      env.WINDOWS_2016_CUSTOM_LABEL ?: "SGX-Windows-2016",
    "acc-win2016-dcap": env.WINDOWS_2016_DCAP_CUSTOM_LABEL ?: "SGXFLC-Windows-2016-DCAP",
    "acc-win2019":      env.WINDOWS_2019_CUSTOM_LABEL ?: "SGX-Windows-2019",
    "acc-win2019-dcap": env.WINDOWS_2019_DCAP_CUSTOM_LABEL ?: "SGXFLC-Windows-2019-DCAP"
]

def windowsLinuxElfBuild(String label, String version, String compiler, String build_type, String lvi_mitigation = 'None', String lvi_mitigation_skip_tests = 'OFF') {
    stage("Ubuntu ${version} SGX1 ${compiler} ${build_type} LVI_MITIGATION=${lvi_mitigation}") {
        node(AGENTS_LABELS["ubuntu-nonsgx"]) {
            timeout(GLOBAL_TIMEOUT_MINUTES) {
                cleanWs()
                checkout scm
                def task = """
                           cmake ${WORKSPACE}                                           \
                               -G Ninja                                                 \
                               -DCMAKE_BUILD_TYPE=${build_type}                         \
                               -DHAS_QUOTE_PROVIDER=ON                                  \
                               -DLVI_MITIGATION=${lvi_mitigation}                       \
                               -DLVI_MITIGATION_BINDIR=/usr/local/lvi-mitigation/bin    \
                               -DLVI_MITIGATION_SKIP_TESTS=${lvi_mitigation_skip_tests} \
                               -Wdev
                           ninja -v
                           """
                oe.ContainerRun("oetools-full-${version}:${DOCKER_TAG}", compiler, task, "--cap-add=SYS_PTRACE")
                stash includes: 'build/tests/**', name: "linux-${label}-${compiler}-${build_type}-lvi_mitigation=${lvi_mitigation}-${version}-${BUILD_NUMBER}"
            }
        }
    }
    stage("Windows ${label} ${build_type} LVI_MITIGATION=${lvi_mitigation}") {
        node(AGENTS_LABELS[label]) {
            timeout(GLOBAL_TIMEOUT_MINUTES) {
                cleanWs()
                checkout scm
                unstash "linux-${label}-${compiler}-${build_type}-lvi_mitigation=${lvi_mitigation}-${version}-${BUILD_NUMBER}"
                bat 'move build linuxbin'
                dir('build') {
                  bat """
                      vcvars64.bat x64 && \
                      cmake.exe ${WORKSPACE} -G Ninja -DADD_WINDOWS_ENCLAVE_TESTS=ON -DBUILD_ENCLAVES=OFF -DHAS_QUOTE_PROVIDER=ON -DCMAKE_BUILD_TYPE=${build_type} -DLINUX_BIN_DIR=${WORKSPACE}\\linuxbin\\tests -DLVI_MITIGATION=${lvi_mitigation} -DLVI_MITIGATION_SKIP_TESTS=${lvi_mitigation_skip_tests} -DNUGET_PACKAGE_PATH=C:/oe_prereqs -Wdev && \
                      ninja -v && \
                      ctest.exe -V -C ${build_type} --timeout ${CTEST_TIMEOUT_SECONDS}
                      """
                }
            }
        }
    }
}

def windowsCrossCompile(String label, String build_type, String has_quote_provider = 'OFF', String lvi_mitigation = 'None', String OE_SIMULATION = "0", String lvi_mitigation_skip_tests = 'OFF') {
    def node_label = AGENTS_LABELS[label]
    if (has_quote_provider == "ON") {
        node_label = AGENTS_LABELS["${label}-dcap"]
    }
    stage("Windows ${label} ${build_type} with SGX ${has_quote_provider} LVI_MITIGATION=${lvi_mitigation}") {
        node(node_label) {
            withEnv(["OE_SIMULATION=${OE_SIMULATION}"]) {
                timeout(GLOBAL_TIMEOUT_MINUTES) {
                    oe.WinCompilePackageTest("build/X64-${build_type}", build_type, has_quote_provider, CTEST_TIMEOUT_SECONDS, lvi_mitigation, lvi_mitigation_skip_tests)
                }
            }
        }
    }
}

properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '90',
                                      artifactNumToKeepStr: '180',
                                      daysToKeepStr: '90',
                                      numToKeepStr: '180')),
            [$class: 'JobRestrictionProperty']])

try{
    oe.emailJobStatus('STARTED')
    if(FULL_TEST_SUITE == "true") {
      stage("Full Test Suite") {
        parallel "Win2016 Ubuntu1604 clang-7 Debug Linux-Elf-build" :       { windowsLinuxElfBuild('acc-win2016-dcap', '16.04', 'clang-7', 'Debug') },
                 "Win2016 Ubuntu1604 clang-7 Release Linux-Elf-build" :     { windowsLinuxElfBuild('acc-win2016-dcap', '16.04', 'clang-7', 'Release') },
                 "Win2016 Ubuntu1604 clang-7 Debug Linux-Elf-build LVI" :   { windowsLinuxElfBuild('acc-win2016-dcap', '16.04', 'clang-7', 'Debug', 'ControlFlow') },
                 "Win2016 Ubuntu1604 clang-7 Release Linux-Elf-build LVI" : { windowsLinuxElfBuild('acc-win2016-dcap', '16.04', 'clang-7', 'Release', 'ControlFlow') },
                 "Win2016 Ubuntu1804 clang-7 Debug Linux-Elf-build" :       { windowsLinuxElfBuild('acc-win2016-dcap', '18.04', 'clang-7', 'Debug') },
                 "Win2016 Ubuntu1804 clang-7 Release Linux-Elf-build" :     { windowsLinuxElfBuild('acc-win2016-dcap', '18.04', 'clang-7', 'Release') },
                 "Win2016 Ubuntu1804 clang-7 Debug Linux-Elf-build LVI" :   { windowsLinuxElfBuild('acc-win2016-dcap', '18.04', 'clang-7', 'Debug', 'ControlFlow') },
                 "Win2016 Ubuntu1804 clang-7 Release Linux-Elf-build LVI" : { windowsLinuxElfBuild('acc-win2016-dcap', '18.04', 'clang-7', 'Release', 'ControlFlow') },
                 "Win2016 Ubuntu1804 gcc Debug Linux-Elf-build" :           { windowsLinuxElfBuild('acc-win2016-dcap', '18.04', 'gcc', 'Debug') },
                 "Win2016 Ubuntu1804 gcc Debug Linux-Elf-build LVI" :       { windowsLinuxElfBuild('acc-win2016-dcap', '18.04', 'gcc', 'Debug', 'ControlFlow') },
                 "Win2016 Sim Debug Cross Compile" :                        { windowsCrossCompile('acc-win2016', 'Debug', 'OFF', 'None', '1') },
                 "Win2016 Sim Release Cross Compile" :                      { windowsCrossCompile('acc-win2016', 'Release','OFF', 'None', '1') },
                 "Win2016 Sim Debug Cross Compile LVI " :                   { windowsCrossCompile('acc-win2016', 'Debug', 'OFF', 'ControlFlow', '1') },
                 "Win2016 Sim Release Cross Compile LVI " :                 { windowsCrossCompile('acc-win2016', 'Release', 'OFF', 'ControlFlow', '1') },
                 "Win2016 Debug Cross Compile with DCAP libs" :             { windowsCrossCompile('acc-win2016', 'Debug', 'ON') },
                 "Win2016 Release Cross Compile with DCAP libs" :           { windowsCrossCompile('acc-win2016', 'Release', 'ON') },
                 "Win2016 Debug Cross Compile DCAP LVI" :                   { windowsCrossCompile('acc-win2016', 'Debug', 'ON', 'ControlFlow') },
                 "Win2016 Release Cross Compile DCAP LVI" :                 { windowsCrossCompile('acc-win2016', 'Release', 'ON', 'ControlFlow') },
                 "Win2019 Ubuntu1604 clang-7 Debug Linux-Elf-build" :       { windowsLinuxElfBuild('acc-win2019-dcap', '16.04', 'clang-7', 'Debug') },
                 "Win2019 Ubuntu1604 clang-7 Release Linux-Elf-build" :     { windowsLinuxElfBuild('acc-win2019-dcap', '16.04', 'clang-7', 'Release') },
                 "Win2019 Ubuntu1604 clang-7 Debug Linux-Elf-build LVI" :   { windowsLinuxElfBuild('acc-win2019-dcap', '16.04', 'clang-7', 'Debug', 'ControlFlow') },
                 "Win2019 Ubuntu1604 clang-7 Release Linux-Elf-build LVI" : { windowsLinuxElfBuild('acc-win2019-dcap', '16.04', 'clang-7', 'Release', 'ControlFlow') },
                 "Win2019 Ubuntu1804 clang-7 Debug Linux-Elf-build" :       { windowsLinuxElfBuild('acc-win2019-dcap', '18.04', 'clang-7', 'Debug') },
                 "Win2019 Ubuntu1804 clang-7 Release Linux-Elf-build" :     { windowsLinuxElfBuild('acc-win2019-dcap', '18.04', 'clang-7', 'Release') },
                 "Win2019 Ubuntu1804 clang-7 Debug Linux-Elf-build LVI" :   { windowsLinuxElfBuild('acc-win2019-dcap', '18.04', 'clang-7', 'Debug', 'ControlFlow') },
                 "Win2019 Ubuntu1804 clang-7 Release Linux-Elf-build LVI" : { windowsLinuxElfBuild('acc-win2019-dcap', '18.04', 'clang-7', 'Release', 'ControlFlow') },
                 "Win2019 Ubuntu1804 gcc Debug Linux-Elf-build" :           { windowsLinuxElfBuild('acc-win2019-dcap', '18.04', 'gcc', 'Debug') },
                 "Win2019 Ubuntu1804 gcc Debug Linux-Elf-build LVI" :       { windowsLinuxElfBuild('acc-win2019-dcap', '18.04', 'gcc', 'Debug', 'ControlFlow') },
                 "Win2019 Sim Debug Cross Compile" :                        { windowsCrossCompile('acc-win2019', 'Debug', 'OFF', 'None', '1') },
                 "Win2019 Sim Release Cross Compile" :                      { windowsCrossCompile('acc-win2019', 'Release','OFF', 'None', '1') },
                 "Win2019 Sim Debug Cross Compile LVI " :                   { windowsCrossCompile('acc-win2019', 'Debug', 'OFF', 'ControlFlow', '1') },
                 "Win2019 Sim Release Cross Compile LVI " :                 { windowsCrossCompile('acc-win2019', 'Release', 'OFF', 'ControlFlow', '1') },
                 "Win2019 Debug Cross Compile with DCAP libs" :             { windowsCrossCompile('acc-win2019', 'Debug', 'ON') },
                 "Win2019 Release Cross Compile with DCAP libs" :           { windowsCrossCompile('acc-win2019', 'Release', 'ON') },
                 "Win2019 Debug Cross Compile DCAP LVI" :                   { windowsCrossCompile('acc-win2019', 'Debug', 'ON', 'ControlFlow') },
                 "Win2019 Release Cross Compile DCAP LVI" :                 { windowsCrossCompile('acc-win2019', 'Release', 'ON', 'ControlFlow') }
      }
    } else {
      stage("PR Testing") {
        parallel "Win2016 Ubuntu1804 clang-7 Release Linux-Elf-build LVI" : { windowsLinuxElfBuild('acc-win2016-dcap', '18.04', 'clang-7', 'Release', 'ControlFlow', 'ON') },
                 "Win2016 Sim Release Cross Compile LVI " :                 { windowsCrossCompile('acc-win2016', 'Release', 'OFF', 'ControlFlow', '1', 'ON') },
                 "Win2016 Debug Cross Compile DCAP LVI" :                   { windowsCrossCompile('acc-win2016', 'Debug', 'ON', 'ControlFlow', '0', 'ON') },
                 "Win2016 Release Cross Compile DCAP LVI" :                 { windowsCrossCompile('acc-win2016', 'Release', 'ON', 'ControlFlow', '0', 'ON') },
                 "Win2019 Ubuntu1804 clang-7 Release Linux-Elf-build LVI" : { windowsLinuxElfBuild('acc-win2019-dcap', '18.04', 'clang-7', 'Release', 'ControlFlow', 'ON') },
                 "Win2019 Sim Release Cross Compile LVI " :                 { windowsCrossCompile('acc-win2019', 'Release', 'OFF', 'ControlFlow', '1', 'ON') },
                 "Win2019 Debug Cross Compile DCAP LVI" :                   { windowsCrossCompile('acc-win2019', 'Debug', 'ON', 'ControlFlow', '0', 'ON') },
                 "Win2019 Release Cross Compile DCAP LVI" :                 { windowsCrossCompile('acc-win2019', 'Release', 'ON', 'ControlFlow', '0', 'ON') }
      }
    }
} catch(Exception e) {
    println "Caught global pipeline exception :" + e
    GLOBAL_ERROR = e
    throw e
} finally {
    currentBuild.result = (GLOBAL_ERROR != null) ? 'FAILURE' : "SUCCESS"
    oe.emailJobStatus(currentBuild.result)
}
