#!/usr/bin/env bash

shopt -s expand_aliases

GDB_SGX_PLUGIN_PATH=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/openenclave/debugger/gdb-sgx-plugin
SGX_LIBRARY_PATH=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/openenclave/debugger

export PYTHONPATH=$GDB_SGX_PLUGIN_PATH
LD_PRELOAD=$SGX_LIBRARY_PATH/liboe_ptrace.so gdb -iex "directory $GDB_SGX_PLUGIN_PATH" -iex "source $GDB_SGX_PLUGIN_PATH/gdb_sgx_plugin.py" -iex "set environment LD_PRELOAD" -iex "add-auto-load-safe-path /usr/lib" "$@"
